### PR TITLE
fix(regexp): fix the capture group count assert to have the correct upper limit

### LINKED ISSUE #4399: Panic `assertion failed: n < 23u64.pow(2) - 1` in `core/engine/src/builtins/regexp/mod.rs`
Rust code
```
fn check_file(path: &str) {
    let Ok(file_content) = fs::read(path) else {
        return;
    };
    println!("Checking file: {path}");
    let mut context = Context::default();

    let _result = context.eval(Source::from_bytes(&file_content));
}
```
when evaluating javascript code(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
num_captures=1000;var regexp_string= "(a)"
for (var i= 0;i < num_captures- 1; i++) { regexp_string+="|()"
} regexp=new RegExp(regexp_string);{regexp.exec()}
```

crashes with this info:
```
thread 'main' (257089) panicked at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/builtins/regexp/mod.rs:1029:9:
assertion failed: n < 23u64.pow(2) - 1
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/07d246fc6dc227903da2955b38a59e060539a485/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/07d246fc6dc227903da2955b38a59e060539a485/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
             at /rustc/07d246fc6dc227903da2955b38a59e060539a485/library/core/src/panicking.rs:145:5
   3: boa_engine::builtins::regexp::RegExp::abstract_builtin_exec
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/builtins/regexp/mod.rs:1029:9
   4: boa_engine::builtins::regexp::RegExp::exec
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/builtins/regexp/mod.rs:847:10
   5: boa_engine::native_function::NativeFunction::call
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/native_function/mod.rs:306:36
   6: boa_engine::native_function::native_function_call
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/native_function/mod.rs:368:18
   7: boa_engine::object::internal_methods::CallValue::resolve
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/object/internal_methods/mod.rs:493:20
   8: boa_engine::vm::opcode::call::Call::operation
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/vm/opcode/call/mod.rs:196:48
   9: boa_engine::vm::opcode::handle_call
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/vm/opcode/mod.rs:313:17
  10: boa_engine::vm::opcode::<impl boa_engine::context::Context>::execute_bytecode_instruction
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/vm/opcode/mod.rs:464:9
  11: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:253:5
  12: boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/vm/mod.rs:649:9
  13: boa_engine::vm::<impl boa_engine::context::Context>::execute_one
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/vm/mod.rs:674:14
  14: boa_engine::vm::<impl boa_engine::context::Context>::run
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/vm/mod.rs:858:24
  15: boa_engine::script::Script::evaluate
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/script.rs:172:30
  16: boa_engine::context::Context::eval
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/context/mod.rs:202:41
  17: boa::check_file
             at ./src/crates/boa/src/main.rs:33:27
  18: boa::main
             at ./src/crates/boa/src/main.rs:22:9
  19: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:253:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

[compressed.zip](https://github.com/user-attachments/files/22087432/compressed.zip)

### PR DESCRIPTION
**Pull request by BDeuDev**
This Pull Request fixes #4399.

It changes the following:

- Raise the limit to what the standard is requiring. It was too low and could be reach easily in real world cases before.

### CODE REVIEW

File: core/engine/src/builtins/regexp/mod.rs [hunk 1]
```diff
@@ -1026,7 +1026,12 @@ impl RegExp {
         let n = match_value.captures.len() as u64;
         // 18. Assert: n = R.[[RegExpRecord]].[[CapturingGroupsCount]].
         // 19. Assert: n < 232 - 1.
-        debug_assert!(n < 23u64.pow(2) - 1);
+        if n >= 23u64.pow(2) - 1 {
+            return Err(JsNativeError::typ()
+                .with_message("Too many capture groups in RegExp")
+                .into());
+        }
+
```
Comment (jedel1043) [inline core/engine/src/builtins/regexp/mod.rs]: I'm pretty certain using an assertion here is the correct thing to do, because the spec [specifies](https://tc39.es/ecma262/multipage/text-processing.html#sec-patterns-static-semantics-early-errors) that there can be no more than 2^32 - 1 capture groups in a compiled regex expression. I think the fix here is to change the wrong assertion to use the correct value.

Also, since this is regex parsing related, we need to verify that this number of capture groups can be parsed by [regress](https://github.com/ridiculousfish/regress), or open an issue otherwise.

**Review by jedel1043 — CHANGES_REQUESTED** [review]

File: core/engine/src/builtins/regexp/mod.rs (hunk 1 above)
Comment (BDeuDev) [reply core/engine/src/builtins/regexp/mod.rs]: Thanks for the feedback!

I’ve updated the code to use
```bash
// 19. Assert: n < 2^32 - 1.
const MAX_CAPTURE_GROUPS: u64 = (1u64 << 32) - 1;
debug_assert!(n < MAX_CAPTURE_GROUPS);

```
instead of the incorrect 23u64.pow(2) - 1.

I also removed the regexp_many_captures_should_return_typeerror test, since this case is now handled by a debug_assert! and no longer results in a runtime JsNativeError. As the spec treats this as an internal invariant, a user-visible error isn’t expected here.

I’ll check how many capture groups regress can actually support and open an issue if it fails before this limit.

Thanks for the help.

**Comment by hansl** [comment]
Thanks for the PR, @BDeuDev!

@jedel1043 could you approve this quickly? I thought my approval was enough but seems not.

**Comment by BDeuDev** [comment]
Thanks @hansl  I'm just getting started with Rust and want to contribute.
