### PR TITLE
Fix enumerable attribute on string length property

### LINKED ISSUE #973: The `length` property of a string is enumerable
**Describe the bug**
The `length` property of a string is enumerable, but it should not.

**To Reproduce**
This JavaScript code reproduces the issue:
```javascript
>> "".propertyIsEnumerable("length")
true
>> new String("").propertyIsEnumerable("length")
true
```

**Expected behavior**
`"".propertyIsEnumerable("length")` and `new String("").propertyIsEnumerable("length")` should be `false`.

**Build environment**

- OS: Windows 10
- Version: 0.10
- Target triple: x86_64-pc-windows-msvc
- Rustc version: rustc 1.48.0 (7eac88abb 2020-11-16)

**Additional context**
None

### PR DESCRIPTION
**Pull request by tofpie**
This Pull Request fixes #973.

It changes the following:

-    The length property of a string is set to non enumerable

### CODE REVIEW

File: boa/src/builtins/string/mod.rs [hunk 1]
```diff
@@ -140,9 +141,11 @@ impl String {
             None => RcString::default(),
         };
 
-        let length = string.encode_utf16().count();
-
-        this.set_field("length", Value::from(length as i32));
+        let length = DataDescriptor::new(
+            Value::from(string.encode_utf16().count() as i32),
```
Comment (RageKnify) [inline boa/src/builtins/string/mod.rs:145]: I know it was already there, but I think we should remove the `as i32`, `From<usize>` is implemeted for `Value` so the conversion is unnecessary.
```suggestion
            Value::from(string.encode_utf16().count()),
```

**Review by RageKnify — CHANGES_REQUESTED** [review]
I think we could remove the unnecessary conversion since we're touching these lines.

**Comment by Razican** [comment]
This looks good :)

## Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,460 | 78,460 | 0 |
  | Passed | 19,374 | 19,380 | **+6** |
  | Ignored | 15,559 | 15,559 | 0 |
  | Failed | 43,527 | 43,521 | **-6** |
  | Panics | 465 | 465 | 0 |
  | Conformance | 24.69 | 24.70 | **+0.01%** |

**Review by Razican — APPROVED** [review]

File: boa/src/value/mod.rs [hunk 2]
```diff
@@ -664,7 +664,11 @@ impl Value {
                     ObjectData::String(string.clone()),
                 ));
                 // Make sure the correct length is set on our new string object
-                object.set("length".into(), string.chars().count().into());
+                object.insert_property(
+                    PropertyKey::String("length".into()),
+                    Value::from(string.chars().count()),
```
Comment (RageKnify) [inline boa/src/value/mod.rs:669]: Just now noticed, this doesn't seem to match the `length` calculation in `boa/src/builtins/string/mod.rs`, there we use `encode_utf16().count()`, so I assume this one might give different results. I'd like someone else to back me on this though.

Comment (RageKnify) [reply boa/src/value/mod.rs:669]: @Razican can you confirm this?

Comment (tofpie) [reply boa/src/value/mod.rs:669]: Seems that `chars().count()` counts the code points, and `encode_utf16().count()` counts the UTF-16 code units, and I think that counting UTF-16 code units is what JavaScript does, but I am not quite sure.

Comment (Razican) [reply boa/src/value/mod.rs:669]: As per [this](https://tc39.es/ecma262/#sec-terms-and-definitions-string-value), the inner value of a String is an array of `u16` code points (which we currently don't use, but at some point we should).

Then, as per [this](https://tc39.es/ecma262/#sec-properties-of-string-instances-length), the `length` property is the number of values (`u16` code points). So it should use `encode_utf16().count()`.

Comment (RageKnify) [reply boa/src/value/mod.rs:669]: That's what I thought, thanks. Just change the method invoked and it should be good to `merge` @tofpie

**Comment by Razican** [comment]
This is blocked on #977.

**Review by RageKnify — APPROVED** [review]

**Comment by Razican** [comment]
#977 was merged, could you rebase?
