### PR TITLE
Fix Stack Overflow for `Debug::fmt`

### LINKED ISSUE #608: `Debug::fmt` Causes Causes a Stack Overflow
**Describe the bug**
For any object that contains `prototype`, `Debug::fmt` will cause a stack overflow. This is especially frustrating when some tests fail, as it can mask the reason for the failure.

**To Reproduce**

Evaluate the following JS and `println!("{:?}", result)`.
```javascript
new Date()
```

**Expected behavior**

Print the debug structure of the value.

**Actual behavior**

A stack overflow occurs.

**Build environment (please complete the following information):**
 - OS: Windows
 - Version: 10
 - Target triple: `x86_64-unknown-windows-msvc`
 - Rustc version: `1.45.1 (c367798cf 2020-07-26)`

### PR DESCRIPTION
**Pull request by jcdickinson**
This Pull Request fixes/closes #608.

It changes the following:
 - Adds RecursionLimiter. This tracks the `GcObject` pointers that have been visited during a `Debug::fmt` call.
 - Adds a test for the stack overflow.

The same object cannot appear twice in the output, by design. JS object graphs tend the be huge, and comprehending a massive data dump is nearly impossible. If the same object appears twice, even if not recursive, it is always elided. The following graph:

```js
let a = {};
a.c = a;
let b = {
 d: a, e: a
};
debug(b);
```

Would print:
```js
{
  d: {
    c: ... // Recursion protected
  },
  e: ... // Will never appear twice
}
```

### CODE REVIEW

File: boa/src/builtins/object/gcobject.rs [hunk 1]
```diff
@@ -61,6 +65,55 @@ impl Display for BorrowError {
...
+}
+
+impl Debug for GcObject {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> std::fmt::Result {
+        let limiter = RecursionLimiter::new(&self);
+
+        if limiter.first {
+            f.debug_tuple("GcObject").field(&self.0).finish()
+        } else {
+            f.write_str("...")
```
Comment (Razican) [inline boa/src/builtins/object/gcobject.rs:112]: I think this makes it clear this is an object:
```suggestion
            f.write_str("{ ... }")
```

File: boa/src/builtins/object/gcobject.rs [hunk 2]
```diff
@@ -61,6 +65,55 @@ impl Display for BorrowError {
     }
 }
 
+struct RecursionLimiter {
+    free: bool,
+    first: bool,
+}
```
Comment (Razican) [inline boa/src/builtins/object/gcobject.rs:71]: Can we add some documentation here? And derive `Debug`, `Clone` and `Copy`, just in case.

File: boa/src/builtins/object/gcobject.rs [hunk 3]
```diff
@@ -61,6 +65,55 @@ impl Display for BorrowError {
...
+
+impl RecursionLimiter {
+    thread_local! {
+        pub static VISITED: RefCell<HashSet<usize>> = RefCell::new(HashSet::new());
+    }
+
+    fn new(o: &GcObject) -> Self {
```
Comment (Razican) [inline boa/src/builtins/object/gcobject.rs:78]: I would add a bit of documentation to this function, explaining what it does.

File: boa/src/builtins/object/gcobject.rs (hunk 2 above)
Comment (jcdickinson) [reply boa/src/builtins/object/gcobject.rs]: `Copy` can't be implemented because `RecursionLimiter` implements `Drop`.

File: boa/src/builtins/object/gcobject.rs [hunk 4]
```diff
@@ -61,6 +65,75 @@ impl Display for BorrowError {
...
+        if self.free {
+            Self::VISITED.with(|hs| hs.borrow_mut().clear());
+        }
+    }
+}
+
+impl RecursionLimiter {
+    thread_local! {
+        pub static VISITED: RefCell<HashSet<usize>> = RefCell::new(HashSet::new());
+    }
```
Comment (Razican) [inline boa/src/builtins/object/gcobject.rs:106]: I think we should add some documentation on what this is and how it works :)

**Comment by jcdickinson** [comment]
Windows check failed with no logs, not sure if I can rerun it?

**Comment by HalidOdat** [comment]
> Windows check failed with no logs, not sure if I can rerun it?

That is strange. Ill rerun it :)
