### PR TITLE
Fix of instructions.rs comment, to_precision impl and rfc changes

### LINKED ISSUE #1038: Seemingly wrong comment for Rational in instruction enum
This comment talks about [loading an `f32` immediate](https://github.com/boa-dev/boa/blob/master/boa/src/vm/instructions.rs#L15), but the [parameter is an `f64`](https://github.com/boa-dev/boa/blob/master/boa/src/vm/instructions.rs#L16).

### PR DESCRIPTION
**Pull request by NathanRoyer**
This Pull Request fixes/closes #1038.

It changes the following:

- ~~applying the changes of [RFC 2700](https://rust-lang.github.io/rfcs/2700-associated-constants-on-ints.html)~~
- fixing the comment mistake from #1038 
- fixing my previously incorrect implementation of Number.prototype.toPrecision

### CODE REVIEW

**Review by RageKnify — CHANGES_REQUESTED** [review]
Code looks good, but I think it'd be nice to have 1 or 2 test cases for the change you did to `round_to_precision` to make sure no regressions are introduced in the future. Is it easy to do that @NathanRoyer?

**Comment by RageKnify** [comment]
test262 numbers actually look bad
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,497 | 78,497 | 0 |
  | Passed | 24,986 | 24,984 | **-2** |
  | Ignored | 15,587 | 15,587 | 0 |
  | Failed | 37,924 | 37,926 | **+2** |
  | Panics | 16 | 16 | 0 |
  | Conformance | 31.83 | 31.83 | **-0.00%** |

**Review by RageKnify — APPROVED** [review]

**Comment by RageKnify** [comment]
@NathanRoyer [this](https://github.com/tc39/test262/tree/42bf3a9f7aed3790dc1d829f290dee033df41c5b/test/built-ins/Number/prototype/toPrecision) directory has the test262 tests for `Number.prototype.toPrecision`, can you take a look to try to understand what is now failing that wasn't before? You could also use the test runner if you prefer.

File: boa/src/builtins/math/mod.rs [hunk 1]
```diff
@@ -36,14 +36,14 @@ impl BuiltIn for Math {
...
+            .property("E", std::f64::consts::E, attribute)
+            .property("LN2", std::f64::consts::LN_2, attribute)
+            .property("LN10", std::f64::consts::LN_10, attribute)
+            .property("LOG2E", std::f64::consts::LOG2_E, attribute)
+            .property("LOG10E", std::f64::consts::LOG10_E, attribute)
             .property("SQRT1_2", 0.5_f64.sqrt(), attribute)
-            .property("SQRT2", f64::consts::SQRT_2, attribute)
-            .property("PI", f64::consts::PI, attribute)
+            .property("SQRT2", std::f64::consts::SQRT_2, attribute)
+            .property("PI", std::f64::consts::PI, attribute)
```
Comment (Razican) [inline boa/src/builtins/math/mod.rs:46]: Why this change? This is giving a bunch of warnings above due to unused imports.

File: boa/src/builtins/string/mod.rs [hunk 2]
```diff
@@ -1162,9 +1162,9 @@ impl String {
         };
         let length = primitive_val.chars().count() as i32;
         // If less than 2 args specified, end is +infinity, the maximum number value.
-        // Using i32::max_value() should be safe because the final length used is at most
+        // Using i32::MAX should be safe because the final length used is at most
         // the number of code units from start to the end of the string,
-        // which should always be smaller or equals to both +infinity and i32::max_value
+        // which should always be smaller or equals to both +infinity and i32::MAX
         let end = if args.len() < 2 {
             i32::MAX
```
Comment (Razican) [inline boa/src/builtins/string/mod.rs:1169]: Actually, here I think it would be best to use `i32::max_value()` in the implementation (as it was in the comment), since it's a const function.

**Review by Razican — CHANGES_REQUESTED** [review]
I suggest changing a couple of things. The code looks good, but as @RageKnify mentions, you should see why there are 2 new tests failing.

Also, it needs a rebase, again.

File: boa/src/builtins/math/mod.rs (hunk 1 above)
Comment (NathanRoyer) [reply boa/src/builtins/math/mod.rs:46]: I didn't change anything here, it's just my fork getting old I guess

File: boa/src/builtins/string/mod.rs (hunk 2 above)
Comment (NathanRoyer) [reply boa/src/builtins/string/mod.rs:1169]: I didn't change anything here, it's just my fork getting old I guess

File: boa/src/builtins/math/mod.rs (hunk 1 above)
Comment (Razican) [reply boa/src/builtins/math/mod.rs:46]: No worries, a rebase should fix it, then.

**Comment by 0x7D2B** [comment]
Latest test262 results:

### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,873 | 78,873 | 0 |
  | Passed | 26,498 | 26,497 | **-1** |
  | Ignored | 15,604 | 15,604 | 0 |
  | Failed | 36,771 | 36,772 | **+1** |
  | Panics | 27 | 27 | 0 |
  | Conformance | 33.60% | 33.59% | **-0.00%** |

It doesn't post the comment but you can find the text in the Update Comment section of test262 results: https://github.com/boa-dev/boa/pull/1135/checks?check_run_id=2649202840

**Review by Razican — APPROVED** [review]
Benchmarks look pretty good, and conformance too. It's good to merge from my side :) tank you!
