### PR TITLE
fix TextDecoder label parsing

### LINKED ISSUE #5135: TextDecoder constructor does not normalize encoding labels
`TextDecoder` is currently matching encoding labels too strictly.

Right now these fail:

```js
new TextDecoder("UTF-8");
new TextDecoder(" utf-16 ");
new TextDecoder("\nutf-8\t");
```

Boa throws a `RangeError` for those, but plain lowercase labels like `new TextDecoder("utf-16")` work.

This looks like the constructor is matching the raw string directly in `core/runtime/src/text/mod.rs` instead of normalizing the label first.

The local WPT file already expects this to work:
- `tests_wpt/encoding/textdecoder-labels.any.js`

That test expects label matching to be:
- ASCII case insensitive
- trimmed for surrounding ASCII whitespace (`' '`, `\t`, `\n`, `\f`, `\r`)

So this seems like a separate issue from the existing `TextDecoder` bugs:
- `#4612` utf-16 decoding correctness
- `#4614` `fatal` handling
- `#4767` `DataView` bounds

This one is specifically about constructor label normalization.

### PR DESCRIPTION
**Pull request by Monti-27**
Fixes #5135.

This makes `TextDecoder` normalize supported encoding labels before matching them.

It now accepts supported labels with ASCII case differences, surrounding ASCII whitespace, and the supported aliases for the UTF-8 and UTF-16 encodings Boa currently implements.

Tests:
- `cargo test -p boa_runtime text --lib`
- `cargo test -p boa_runtime --lib`
- `cargo clippy -p boa_runtime --all-features --all-targets -- -D warnings`

### CODE REVIEW

File: core/runtime/src/text/mod.rs [hunk 1]
```diff
@@ -34,6 +34,51 @@ pub enum Encoding {
...
+
+const UTF_16LE_LABELS: &[&str] = &[
+    "csunicode",
+    "iso-10646-ucs-2",
+    "ucs-2",
+    "unicode",
+    "unicodefeff",
+    "utf-16",
+    "utf-16le",
+];
```
Comment (jedel1043) [inline core/runtime/src/text/mod.rs]: This might be simplified with an array of tuples `[(&str, Encoding)]`

File: core/runtime/src/text/tests.rs [hunk 2]
```diff
@@ -288,6 +288,66 @@ fn decoder_bom_ignore_bom_false(encoding: &'static str, bytes: &'static [u8]) {
...
+    text::register(None, context).unwrap();
+
+    run_test_actions_with(
+        [
+            TestAction::run(indoc! {r#"
+                threw = false;
+                try {
+                    new TextDecoder(" utf-32 ");
+                } catch (e) {
+                    threw = e instanceof RangeError;
```
Comment (jedel1043) [inline core/runtime/src/text/tests.rs]: No need to manually check if it threw, you can do an `if !(e instanceof RangeError) { throw e }` to reraise the exception and the suite should automatically report that the run failed

**Review by jedel1043 — CHANGES_REQUESTED** [review]
Looks good! I just have a couple of nitpicks

File: core/runtime/src/text/mod.rs (hunk 1 above)
Comment (Monti-27) [reply core/runtime/src/text/mod.rs]: makes sense i can fold that into one small label table here

File: core/runtime/src/text/tests.rs (hunk 2 above)
Comment (Monti-27) [reply core/runtime/src/text/tests.rs]: good point

**Review by jedel1043 — APPROVED** [review]
Looks great!

**Comment by Monti-27** [comment]
> Looks great!

thanks mentor !!
