### PR TITLE
Fix display for nodes

### LINKED ISSUE #1311: `StatementList` display is broken
Currently, `StatementList`, `Node`, and all node types implement `fmt::Display`. This is meant to pretty-print the AST that was parsed from a JavaScript source file. Based on the current implementation, it looks like it is meant to generate javascript-like source code. However, it is very broken. Example:

Original source:
```js
a = 5

function i_am_function(a, b) {
  for (i = 0; i < 10; i++) {
    a += b;
  }
  console.log(a);
}

arr = [1, 2, 3];

for (a in arr) {
  arr[1] = a;
}

```
Display output (on `StatementList`):
```js
    function i_am_function(a, b) {{                    for (i = 0;i < 10;++i) {
{
                                            a += b;
                }};
                    console.log(a);
}
;
    a = 5;
    arr = [1, 2, 3];
    for (a in arr) {{
                            arr[1] = a;
        }};
```
(I know this is nonsense code. I just needed an example)

Most of this makes sense. The actual JavaScript it outputs almost matches what was inputted. However, it looks terrible.

I am working on fixing this right now, and I'm just making this issue to make sure this is an acceptable feature. I plan to make a PR if it is something that should be fixed.

### PR DESCRIPTION
**Pull request by macmv**
This Pull Request fixes/closes #1311 

This is a collection of fixes for the `fmt::Display` functions on various nodes. With this PR, you can print a `StatementList` to stdout in nearly the same format as the source code.

### CODE REVIEW

**Review by Razican — COMMENTED** [review]
Thank you for these contributions!! This will look much better now. Could we add some tests to make sure new changes don't break it?

**Comment by macmv** [comment]
Tests take a long time to write. I'm going to work on this later tonight. I all the tests I've written so far in the `tests.rs` file in each node directory (for example, `syntax/ast/node/call/tests.rs`). There is also a utility function for testing all of these, which is at the bottom of `syntax/ast/node/mod.rs`. I wasn't really sure where else to put it, and I made sure its `#[cfg(test)]`.

**Comment by Razican** [comment]
> Tests take a long time to write. I'm going to work on this later tonight. I put all the tests I've written so far in the `tests.rs` file in each node directory (for example, `syntax/ast/node/call/tests.rs`). There is also a utility function for testing all of these, which is at the bottom of `syntax/ast/node/mod.rs`. I wasn't really sure where else to put it, and I made sure its `#[cfg(test)]`.

Something that could simplify writing the tests would be to add a folder with some code snippets to test. That way, you can just load each of them in a test and compare the outputs.

**Comment by macmv** [comment]
I think setting up a loader for a bunch of files would just take more time. The most time-consuming part of these tests was just setting up the testing function, and re-writing my previous tests.

File: boa/src/syntax/ast/node/object/mod.rs [hunk 1]
```diff
@@ -53,24 +56,32 @@ impl Object {
...
+        let indentation = "    ".repeat(indent + 1);
         for property in self.properties().iter() {
             match property {
                 PropertyDefinition::IdentifierReference(key) => {
-                    write!(f, "{}    {},", indent, key)?;
+                    writeln!(f, "{}{},", indentation, key)?;
                 }
                 PropertyDefinition::Property(key, value) => {
-                    write!(f, "{}    {}: {},", indent, key, value)?;
+                    dbg!(&value);
```
Comment (RageKnify) [inline boa/src/syntax/ast/node/object/mod.rs:66]: Forgotten `dbg!()`?

**Comment by Razican** [comment]
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 26,801 | 26,801 | 0 |
  | Ignored | 15,628 | 15,628 | 0 |
  | Failed | 36,468 | 36,468 | 0 |
  | Panics | 0 | 0 | 0 |
  | Conformance | 33.97% | 33.97% | 0.00% |

File: boa/src/syntax/ast/node/object/mod.rs (hunk 1 above)
Comment (macmv) [reply boa/src/syntax/ast/node/object/mod.rs]: Whoops. Thats removed now. The Object definition has been more complicated than I thought, so I've added a couple extra `dbg!()` calls here and there.

**Comment by macmv** [comment]
Alright, I've finished up the tests. The world is beautiful, and everything passes, and a lot of bugs were fixed. I think I covered everything, but [tarpaulin](https://github.com/xd009642/tarpaulin) is hard to use, so I am not entirely sure that I didn't miss something.

File: boa/src/syntax/ast/node/operator/tests.rs [hunk 2]
```diff
@@ -1,4 +1,4 @@
-use crate::exec;
+use crate::{exec, parse};
```
Comment (RageKnify) [inline boa/src/syntax/ast/node/operator/tests.rs:1]: Some of the actions are complaining about `parse` not being used, I assume you used it at some point and then refactored the way you did the tests and stopped needing it.

**Review by RageKnify — APPROVED** [review]
Minor thing to avoid compiler warnings the rest looks great.

File: boa/src/syntax/ast/node/mod.rs [hunk 3]
```diff
@@ -588,3 +602,38 @@ pub enum MethodDefinitionKind {
...
+    let characters_to_remove = first_line.len() - trimmed_first_line.len();
+
+    let scenario = source
+        .lines()
+        .map(|l| &l[characters_to_remove..]) // Remove preceding whitespace from each line
+        .collect::<Vec<&'static str>>()
+        .join("\n");
+    let result = format!("{}", crate::parse(&scenario, false).unwrap());
+    if scenario != result {
+        print!("========= Expected:\n{}", scenario);
```
Comment (Razican) [inline boa/src/syntax/ast/node/mod.rs:632]: I would use `eprint!()` here, in order to print to steer, since this would be an error.

**Review by Razican — APPROVED** [review]
I think this is almost ready. Great work!!! Check my comment and @RageKnify's :)

**Comment by macmv** [comment]
I've fixed both of those issues. Thank you for pointing those out. Also, `cargo fix` didn't do anything except remove that unused import, so I don't think there are any other warnings I created.
