### PR TITLE
Fix compilation for targets without `AtomicU64`

### LINKED ISSUE #2599: MIPS 32-bit target without Atomic{I,U}64
https://github.com/Borber/seam/actions/runs/4154490037/jobs/7186917428#step:5:227 

How should I fix this problem

### PR DESCRIPTION
**Pull request by jedel1043**
Closes #2599 
Also addresses the clippy lint that we had disabled temporarily.

### CODE REVIEW

File: boa_engine/src/symbol.rs [hunk 1]
```diff
@@ -33,23 +33,22 @@ use num_enum::{IntoPrimitive, TryFromPrimitive};
...
 use std::{
     hash::{Hash, Hasher},
-    sync::{
-        atomic::{AtomicU64, Ordering},
-        Arc,
-    },
+    sync::{atomic::Ordering, Arc},
 };
 
+use portable_atomic::AtomicUsize;
```
Comment (Razican) [inline boa_engine/src/symbol.rs:39]: Wouldn't `std::sync::atomic::AtomicUsize` work?

**Review by Razican — APPROVED** [review]
Thanks!!

File: boa_engine/src/symbol.rs [hunk 2]
```diff
@@ -34,7 +34,7 @@ use num_enum::{IntoPrimitive, TryFromPrimitive};
 use std::{
     hash::{Hash, Hasher},
     sync::{
-        atomic::{AtomicU64, Ordering},
+        atomic::{AtomicUsize, Ordering},
```
Comment (HalidOdat) [inline boa_engine/src/symbol.rs:37]: The problem with `usize` is that on 32-bit architectures this is a `u32`, which isn't big enough, we can reach the max in about `15s`. With `u64` will take more than a century.

This effects the whole program, so all threads can't create `JsSymbol`s

Comment (jedel1043) [reply boa_engine/src/symbol.rs:37]: So we use `portable_atomic::AtomicU64`? I considered that alternative, but opted for this because `AtomicU64` is a lot slower on platforms without 8 byte atomics, since they have to get a global lock to do operations.

Comment (jedel1043) [reply boa_engine/src/symbol.rs:37]: I think the question would be: do we want to prioritise flexibility or speed?

Comment (jedel1043) [reply boa_engine/src/symbol.rs:37]: Thinking about it more thoroughly, I don't think we need to pick one of them, we can just leave the decision to our users!

A "fast-symbols" feature that selects `AtomicUsize` if it is enabled and fallbacks to `AtomicU64` otherwise should be enough. What do you think?

Comment (jedel1043) [reply boa_engine/src/symbol.rs:37]: You could also argue that symbols are not as prevalent in most JS programs, so it would be pretty rare to have `u32::MAX` symbols alive at the same time.

Comment (raskad) [reply boa_engine/src/symbol.rs:37]: > I think the question would be: do we want to prioritise flexibility of use or speed?

I'm not 100% into the topic at the moment, but I'd guess 8 byte atomics are common on most platforms nowdays? I would say we go for the flexibility right now as  the speed cost would not affect most users. If we notice it to be a problem we could always add optimizations or even give the users the option to choose, right?

Comment (jedel1043) [reply boa_engine/src/symbol.rs:37]: > > I think the question would be: do we want to prioritise flexibility of use or speed?
> 
> I'm not 100% into the topic at the moment, but I'd guess 8 byte atomics are common on most platforms nowdays? I would say we go for the flexibility right now as  the speed cost would not affect most users. If we notice it to be a problem we could always add optimizations or even give the users the option to choose, right?

Ok, since it seems like both of you prefer the `AtomicU64` option, I'll prioritise flexibility then. I think it shouldn't affect performance for most programs because most of them don't create a lot of symbols consecutively.

Comment (HalidOdat) [reply boa_engine/src/symbol.rs:37]: Yes, lets continue with `AtomicU64`, if we need to we can change it in the future :)

File: boa_engine/src/lib.rs [hunk 3]
```diff
@@ -123,9 +123,11 @@
 
     // Add temporarily - Needs addressing
     clippy::missing_panics_doc,
-    clippy::arc_with_non_send_sync,
 )]
 
+#[cfg(not(target_has_atomic = "ptr"))]
+compile_error!("Boa requires a lock free `AtomicUsize` in order to work properly.");
+
```
Comment (HalidOdat) [inline boa_engine/src/lib.rs:130]: We don't need this, right?

**Review by HalidOdat — APPROVED** [review]
Besides the comment below, this looks good to me! :)

File: boa_engine/src/lib.rs (hunk 3 above)
Comment (HalidOdat) [reply boa_engine/src/lib.rs:130]: I see, forgot that `Arc` uses `AtomicUsize` internally 😅 . thanks for the clarification!

**Review by HalidOdat — APPROVED** [review]
Looks perfect to me! :)
