### PR TITLE
Remove `Expression::FormalParameterList`

### LINKED ISSUE #4403: Panic `a span cannot start after its end` in `core/parser/src/parser/expression/unary.rs`
Rust code
```
fn check_file(path: &str) {
    let Ok(file_content) = fs::read(path) else {
        return;
    };
    println!("Checking file: {path}");
    let mut context = Context::default();

    let _result = context.eval(Source::from_bytes(&file_content));
}
```
when evaluating javascript code(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
(!()=>
```

crashes with this info:
```
thread 'main' (431959) panicked at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/unary.rs:165:21:
a span cannot start after its end
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/07d246fc6dc227903da2955b38a59e060539a485/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/07d246fc6dc227903da2955b38a59e060539a485/library/core/src/panicking.rs:75:14
   2: boa_ast::position::Span::new
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/ast/src/position.rs:177:9
   3: <boa_parser::parser::expression::unary::UnaryExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/unary.rs:165:21
   4: <boa_parser::parser::expression::assignment::exponentiation::ExponentiationExpression as boa_parser::parser::TokenParser<R>>::parse
   5: <boa_parser::parser::expression::MultiplicativeExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
   6: <boa_parser::parser::expression::AdditiveExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
   7: <boa_parser::parser::expression::ShiftExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
   8: <boa_parser::parser::expression::RelationalExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:552:70
   9: <boa_parser::parser::expression::EqualityExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  10: <boa_parser::parser::expression::BitwiseANDExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  11: <boa_parser::parser::expression::BitwiseXORExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  12: <boa_parser::parser::expression::BitwiseORExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  13: <boa_parser::parser::expression::ShortCircuitExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:252:18
  14: <boa_parser::parser::expression::assignment::conditional::ConditionalExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/assignment/conditional.rs:64:14
  15: <boa_parser::parser::expression::assignment::AssignmentExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/assignment/mod.rs:155:14
  16: <boa_parser::parser::expression::Expression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:144:14
  17: <boa_parser::parser::expression::primary::CoverParenthesizedExpressionAndArrowParameterList as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/primary/mod.rs:375:22
  18: <boa_parser::parser::expression::primary::PrimaryExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/primary/mod.rs:171:18
  19: <boa_parser::parser::expression::left_hand_side::member::MemberExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/left_hand_side/member.rs:227:18
  20: <boa_parser::parser::expression::left_hand_side::LeftHandSideExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/left_hand_side/mod.rs:148:18
  21: <boa_parser::parser::expression::update::UpdateExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/update.rs:149:14
  22: <boa_parser::parser::expression::assignment::exponentiation::ExponentiationExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/assignment/exponentiation.rs:76:71
  23: <boa_parser::parser::expression::MultiplicativeExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  24: <boa_parser::parser::expression::AdditiveExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  25: <boa_parser::parser::expression::ShiftExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  26: <boa_parser::parser::expression::RelationalExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:552:70
  27: <boa_parser::parser::expression::EqualityExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  28: <boa_parser::parser::expression::BitwiseANDExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  29: <boa_parser::parser::expression::BitwiseXORExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  30: <boa_parser::parser::expression::BitwiseORExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:84:67
  31: <boa_parser::parser::expression::ShortCircuitExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:252:18
  32: <boa_parser::parser::expression::assignment::conditional::ConditionalExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/assignment/conditional.rs:64:14
  33: <boa_parser::parser::expression::assignment::AssignmentExpression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/assignment/mod.rs:155:14
  34: <boa_parser::parser::expression::Expression as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/expression/mod.rs:144:14
  35: <boa_parser::parser::statement::expression::ExpressionStatement as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/statement/expression/mod.rs:101:71
  36: <boa_parser::parser::statement::Statement as boa_parser::parser::TokenParser<R>>::parse
  37: <boa_parser::parser::statement::StatementListItem as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/statement/mod.rs:457:18
  38: <boa_parser::parser::statement::StatementList as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/statement/mod.rs:316:22
  39: <boa_parser::parser::ScriptBody as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/mod.rs:398:10
  40: <boa_parser::parser::ScriptParser as boa_parser::parser::TokenParser<R>>::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/mod.rs:329:70
  41: boa_parser::parser::Parser<R>::parse_script_with_source
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/parser/src/parser/mod.rs:167:58
  42: boa_engine::script::Script::parse
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/script.rs:94:41
  43: boa_engine::context::Context::eval
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/8ea37c6/core/engine/src/context/mod.rs:202:9
  44: boa::check_file
             at ./src/crates/boa/src/main.rs:33:27
  45: boa::main
             at ./src/crates/boa/src/main.rs:22:9
  46: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:253:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

[compressed.zip](https://github.com/user-attachments/files/22087575/compressed.zip)

### PR DESCRIPTION
**Pull request by hpp2334**
This Pull Request fixes #4403 .

It changes the following:

- Remove `Expression::FormalParameterList`
- Introduce a new structure, `FormalParameterListOrExpression`, as the output for certain parsers (e.g., `MemberExpression`, `UnaryExpression`).
- Throw an error early in cases where it's known that `CPEAAPL` cannot be interpreted as a `FormalParameterList`.

I'm uncertain about this change. It adds complexity to the parser.

### CODE REVIEW

File: core/ast/src/position.rs [hunk 1]
```diff
@@ -153,6 +153,7 @@ impl Debug for Span {
 }
 
 impl Span {
+    #[allow(dead_code)]
     pub(crate) const EMPTY: Span = Span {
         start: Position::new(1, 1),
         end: Position::new(1, 1),
```
Comment (HalidOdat) [inline core/ast/src/position.rs]: Suggestion: If it's not used anywhere, I'd say just delete it :smile:

File: core/parser/src/parser/expression/assignment/mod.rs [hunk 2]
```diff
@@ -151,11 +154,14 @@ where
...
-        let mut lhs = ConditionalExpression::new(self.allow_in, self.allow_yield, self.allow_await)
+        let lhs = ConditionalExpression::new(self.allow_in, self.allow_yield, self.allow_await)
             .parse(cursor, interner)?;
 
         // If the left hand side is a parameter list, we must parse an arrow function.
-        if let Expression::FormalParameterList(parameters) = lhs {
+        if let FormalParameterListOrExpression::FormalParameterList {
+            fpl: parameters, ..
+        } = lhs
+        {
```
Comment (HalidOdat) [inline core/parser/src/parser/expression/assignment/mod.rs]: Remark: Could match here, for both variants (`FormalParameterList`, and `Expression`) to avoid the `expect_expression()` below.

Something like:

```rust
let mut lhs = match lhs {
    FormalParameterListOrExpression::FormalParameterList { .. } => {
        /* ... */
    }
    FormalParameterListOrExpression::Expression(lhs) => lhs,
};
```

File: core/parser/src/parser/expression/mod.rs [hunk 3]
```diff
@@ -73,30 +75,35 @@ macro_rules! expression {
...
                 if $goal.is_some() {
                     cursor.set_goal($goal.unwrap());
                 }
 
-                let mut lhs = $lower::new($( self.$low_param ),*).parse(cursor, interner)?;
+                let lhs = $lower::new($( self.$low_param ),*).parse(cursor, interner)?;
+                let mut lhs = match lhs {
+                    FormalParameterListOrExpression::Expression(expression) => expression,
+                    other => return Ok(other)
+                };
```
Comment (HalidOdat) [inline core/parser/src/parser/expression/mod.rs]: Remark: It might be a bit cleaner to use let-else here.
```suggestion
                let FormalParameterListOrExpression::Expression(mut lhs) = lhs else {
                    return Ok(lhs);
                };
```

File: core/ast/src/position.rs (hunk 1 above)
Comment (hpp2334) [reply core/ast/src/position.rs]: This is used in tests now, not production. Removing it will break the test build. So I add `#[allow(dead_code)]` here.

Comment (HalidOdat) [reply core/ast/src/position.rs]: I see, you could mark it as `#[cfg(test)]` that way if we remove the reference to it on the tests, we will get an unused warning.

Comment (hpp2334) [reply core/ast/src/position.rs]: I've finally replaced all usages of SPAN::EMPTY.
