### PR TITLE
Bug fix: regex started with `/=` parsed as `AssignDiv`

### LINKED ISSUE #3329: RegExp /=/ not parsed as such in certain locations
**Describe the bug**
The code `() => /=/` (and certain other uses of the RegExp literal `/=/`) raises a SyntaxError.

**To Reproduce**
Execute the following JavaScript:
```javascript
() => /=/
```

**Expected behavior**
This code should be parsed as an arrow function expression with no arguments that returns a RegExp that matches the character `=`. (semantically equivalent to `() => new RegExp("=")`)

**Build environment (please complete the following information):**

- OS: Artix Linux
- Version: rolling
- Target triple: `x86_64-unknown-linux-gnu`
- Rustc version: `rustc 1.72.1 (d5c2e9c34 2023-09-13)`

**Additional context**
Notably, `return /=/` inside of an arrow function errors, but not inside of a `function` function.
```javascript
() => {return /=/} // error
(function() {return /=/}) // fine!
```
Other uses of the literal `/=/` that error include:
```javascript
let a = 5; /=/; // should construct RegExp and set a to 5, instead errors
+/=/ // should evaluate to NaN
class A extends /=/ {} // should error out because /=/ is not a constructor, not because of syntax
```

### PR DESCRIPTION
**Pull request by Nikita-str**
This Pull Request closes #3329

### CODE REVIEW

File: core/engine/src/tests/operators.rs [hunk 1]
```diff
@@ -600,6 +600,15 @@ fn delete_in_strict_function_returned() {
     )]);
 }
 
+#[test]
+fn regex_slash_eq() {
+    run_test_actions([
+        TestAction::assert_eq("+/=/", JsValue::nan()),
+        TestAction::assert_eq("var a = 5; /=/; a", 5),
+        TestAction::assert_eq("x = () => /=/;\n\"a=b\".match(x())[0]", js_str!("=")),
```
Comment (raskad) [inline core/engine/src/tests/operators.rs:608]: Can you expand on the `\n` here`? Is there a specific reason for it?
When I try to run `x = () => /=/;"a=b".match(x())[0]` on the current main branch I get a syntax error, in node I get `=` as expected.

**Review by raskad — APPROVED** [review]
Nice fix, I just have one question about one test.

File: core/engine/src/tests/operators.rs (hunk 1 above)
Comment (Nikita-str) [reply core/engine/src/tests/operators.rs:608]: The syntax error is not expected here:
`/=/` is a valid regex;
so `x = () => /=/` is also valid as arrow function that returns mentioned regex;
so `x = () => /=/;"a=b".match(x())[0]` should to create arrow fn `x` that return regex and then call for `"a=b"` match function with `x()` arg that will be the same as `"a=b".match(/=/)` that return `["="]` and `[0]` for it will return `"="`.
So `x = () => /=/;"a=b".match(x())[0]` also should return `"="`

Comment (raskad) [reply core/engine/src/tests/operators.rs:608]: Yeah that's all clear, I was just wondering about the line break `\n`.

Comment (Nikita-str) [reply core/engine/src/tests/operators.rs:608]: Oh sorry, I misunderstood your question.

No, there is no special reason.
The test have such form because firstly I checked bug in js file, and this was on two diff lines so seems like I just moved new line with the test from js.

**Review by jedel1043 — APPROVED** [review]
Looks great! Thank you!
