### PR TITLE
Fix nested class scope index

### LINKED ISSUE #4555: Panic `index out of bounds: the len is 0 but the index is 0` in `core/engine/src/vm/opcode/define/mod.rs`
Rust code
```
fn check_file(path: &str) {
    let Ok(file_content) = fs::read(path) else {
        return;
    };
    println!("Checking file: {path}");
    let mut context = Context::default();

    let _result = context.eval(Source::from_bytes(&file_content));
}
```
when evaluating javascript code(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
class{constructor(){class D{}}}
```

crashes with this info:
```
thread 'main' (189534) panicked at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/5cbbb72/core/engine/src/vm/opcode/define/mod.rs:82:39:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/3ff30e7eafc1da7104c3960187d17939172428ed/library/std/src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/3ff30e7eafc1da7104c3960187d17939172428ed/library/core/src/panicking.rs:80:14
   2: core::panicking::panic_bounds_check
             at /rustc/3ff30e7eafc1da7104c3960187d17939172428ed/library/core/src/panicking.rs:271:5
   3: <usize as core::slice::index::SliceIndex<[core::option::Option<boa_engine::value::JsValue>]>>::index_mut
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:278:14
   4: <[core::option::Option<boa_engine::value::JsValue>] as core::ops::index::IndexMut<usize>>::index_mut
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:31:15
   5: <alloc::vec::Vec<core::option::Option<boa_engine::value::JsValue>> as core::ops::index::IndexMut<usize>>::index_mut
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3666:9
   6: <boa_engine::environments::runtime::declarative::PoisonableEnvironment>::set
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/5cbbb72/core/engine/src/environments/runtime/declarative/mod.rs:310:35
   7: <boa_engine::vm::opcode::define::PutLexicalValue>::operation
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/5cbbb72/core/engine/src/vm/opcode/define/mod.rs:82:39
   8: boa_engine::vm::opcode::handle_put_lexical_value
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/5cbbb72/core/engine/src/vm/opcode/mod.rs:313:17
   9: <boa_engine::context::Context>::execute_bytecode_instruction
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/5cbbb72/core/engine/src/vm/opcode/mod.rs:464:9
  10: <<boa_engine::context::Context>::execute_bytecode_instruction as core::ops::function::FnOnce<(&mut boa_engine::context::Context, boa_engine::vm::opcode::Opcode)>>::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  11: <boa_engine::context::Context>::execute_instruction::<<boa_engine::context::Context>::execute_bytecode_instruction>
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/5cbbb72/core/engine/src/vm/mod.rs:640:9
  12: <boa_engine::context::Context>::execute_one::<<boa_engine::context::Context>::execute_bytecode_instruction>
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/5cbbb72/core/engine/src/vm/mod.rs:666:14
  13: <boa_engine::context::Context>::run
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/5cbbb72/core/engine/src/vm/mod.rs:850:24
  14: <boa_engine::script::Script>::evaluate
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/5cbbb72/core/engine/src/script.rs:172:30
  15: <boa_engine::context::Context>::eval::<boa_parser::source::utf8::UTF8Input<&[u8]>>
             at /home/runner/.cargo/git/checkouts/boa-126d820dff07bf57/5cbbb72/core/engine/src/context/mod.rs:204:41
  16: boa::check_file
             at ./src/crates/boa/src/main.rs:33:27
  17: boa::main
             at ./src/crates/boa/src/main.rs:22:9
  18: <fn() as core::ops::function::FnOnce<()>>::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
timeout: the monitored command dumped core
```

[compressed.zip](https://github.com/user-attachments/files/23849550/compressed.zip)

### PR DESCRIPTION
**Pull request by regularkevvv**
This Pull Request closes #4555.

**How to reproduce:**

```js
// Class expression constructor with nested class
new (class{constructor(){class D{}}})();

// Static block with nested class
(class{static{class D{}}});
```

Both crash with: `index out of bounds: the len is 0 but the index is 0`

**Additional patterns that trigger the bug:**

```js
// Constructor variants
[new (class{constructor(){class D{}}})()]
({x: new (class{constructor(){class D{}}})()})
new (class{ m(){} constructor(){class D{}} })()
new (class{ static m(){} constructor(){class D{}} })()
new (class{ get g(){return 1} constructor(){class D{}} })()
new (class{ #m(){} constructor(){class D{}} })()
new (class{ ['p']=1; constructor(){class D{}} })()

// Static block variants
(class{ static{let v=1} static{class D{}} })
(class{static{let v=1;((v)=>{class D{}})(v)}})
```

**It changes the following:**

- Fixed `ScopeIndexVisitor::visit_class_expression_mut` to call `visit_function_like` with `force_function_scope: true` for constructors, matching `visit_class_declaration_mut`. Previously it called `visit_function_expression_mut`, which forwards `contains_direct_eval()` as the last argument (not an unconditional `false`). For class constructors we must force function scope regardless of direct eval to match bytecode compilation.
- Fixed `ScopeIndexVisitor::visit_class_element_mut` for `StaticBlock` to pass `true` for `force_function_scope`. Previously it passed `contains_direct_eval`, which is correct for escape analysis but not for scope-index layout in `ScopeIndexVisitor`.
- This change only affects scope-index layout (`ScopeIndexVisitor`). Escape analysis still uses `contains_direct_eval` in `BindingEscapeAnalyzer`, so direct eval-based binding escape behavior is unchanged.

Both class expression constructors and static blocks always have `HAS_FUNCTION_SCOPE` set during bytecode compilation, so the scope analyzer must account for this when assigning scope indices.

Added two regression tests covering both cases

### CODE REVIEW

File: core/ast/src/scope_analyzer.rs [hunk 1]
```diff
@@ -1479,17 +1486,14 @@ impl<'ast> VisitorMut<'ast> for ScopeIndexVisitor {
                 self.index = index;
                 ControlFlow::Continue(())
             }
-            ClassElement::StaticBlock(node) => {
-                let contains_direct_eval = contains(node.statements(), ContainsSymbol::DirectEval);
```
Comment (jedel1043) [inline core/ast/src/scope_analyzer.rs:1483]: Why remove `contains_direct_eval`? IIRC this makes it such that the scope analyzer can determine if a binding escapes the function. Passing `true` is technically correct, but it would disable all escape analysis for all static blocks, even if the bindings within it are local.

**Comment by jedel1043** [comment]
The `force_function_scope` parameter in `visit_function_like` doesn't exist...

File: core/ast/src/scope_analyzer.rs (hunk 1 above)
Comment (regularkevvv) [reply core/ast/src/scope_analyzer.rs:1483]: Hi @jedel1043 thanks for reviewing!, please correct me if I'm wrong (just starting to contribute with the project): this change only affects the implementation of `VisitorMut` at `ScopeIndexVisitor`, not `BindingEscapeAnalyzer` which is the part that computes `contains_direct_eval` for static blocks and uses it to escape bindings when needed.
Also just updated the description, thanks for catching that and apologies 🥲
Let me know if this looks good to you, currently I'm just fixing things as I find them while working on a project that points to Boa's `main`, this is a great project!

Comment (jedel1043) [reply core/ast/src/scope_analyzer.rs:1483]: Ohh I think I got it. `ScopeIndexVisitor` doesn't need to care about `eval` calls because it's only to get the correct scope index of each environment. Yeah, this seems to be correct then.
