### PR TITLE
fix(boa): fixes panic on bigint size

### LINKED ISSUE #1401: panicked at 'memory overflow'
**Describe the bug**
thread 'main' panicked at 'memory overflow'

**To Reproduce**
Input: 
`4n**44444444444444434444444434644446444444444444n`

Code:
```rust
fn main(){
    // let data = input

    let mut context = Context::new();
    context.eval(data);

}
```

Output
```
thread 'main' panicked at 'memory overflow', /home/xsh/code/rust-compiler/src/libstd/macros.rs:13:23
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
             at /home/xsh/code/rust-compiler/src/libstd/panicking.rs:456
   7: num_bigint::biguint::power::<impl num_traits::pow::Pow<&num_bigint::biguint::BigUint> for num_bigint::biguint::BigUint>::pow
             at /home/xsh/code/rust-compiler/src/libstd/macros.rs:13
   8: num_bigint::biguint::power::<impl num_traits::pow::Pow<num_bigint::biguint::BigUint> for num_bigint::biguint::BigUint>::pow
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.3.2/src/biguint/power.rs:35
   9: num_bigint::bigint::power::<impl num_traits::pow::Pow<num_bigint::biguint::BigUint> for num_bigint::bigint::BigInt>::pow
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.3.2/src/bigint/power.rs:30
  10: boa::builtins::bigint::operations::<impl boa::builtins::bigint::BigInt>::pow
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/builtins/bigint/operations.rs:11
  11: boa::value::operations::<impl boa::value::Value>::pow
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/value/operations.rs:184
  12: <boa::syntax::ast::node::operator::bin_op::BinOp as boa::exec::Executable>::run
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/syntax/ast/node/operator/bin_op/mod.rs:115
  13: <boa::syntax::ast::node::Node as boa::exec::Executable>::run
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/syntax/ast/node/mod.rs:318
  14: <boa::syntax::ast::node::statement_list::StatementList as boa::exec::Executable>::run
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/syntax/ast/node/statement_list/mod.rs:71
  15: boa::context::Context::eval
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/context.rs:717
```

**Expected behavior**
eval should return error properly instead of panic

**Build environment (please complete the following information):**

- OS: Ubuntu
- Version: 18.04
- Target triple: x86_64-unknown-linux-gnu
- Rustc version: rustc 1.46.0

**Additional context**

### PR DESCRIPTION
**Pull request by neeldug**
This Pull Request fixes/closes #1401.

It changes the following:

- adds crude memory check on bigint bitsize
- throws range error if exceeds 1B bits

### CODE REVIEW

**Comment by neeldug** [comment]
@Razican @RageKnify wanted to get your thoughts since I wanted to do this approx memory check using Log2, but it's unimplemented on `num-bigint`, and the [issue](https://github.com/rust-num/num-bigint/issues/57) seems untouched, I'd give it a go but haven't got the time to create the docs/efficient implementation at the time.

**Comment by neeldug** [comment]
Weirdly enough this caused this to happen:

### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 28,323 | 28,322 | **-1** |
  | Ignored | 15,614 | 15,614 | 0 |
  | Failed | 34,960 | 34,961 | **+1** |
  | Panics | 2 | 2 | 0 |
  | Conformance | 35.90% | 35.90% | **-0.00%** |
  
  <details><summary><b>Broken tests:</b></summary>
  
  ```
  test/built-ins/Map/prototype/set/append-new-values-normalizes-zero-key.js (previously Passed)
  ```
  </details>

File: boa/src/bigint.rs [hunk 1]
```diff
@@ -169,6 +169,15 @@ impl JsBigInt {
             return Err(context.construct_range_error("BigInt negative exponent"));
         };
 
+        let num_bits = (y.to_f64().expect("Unable to convert from BigUInt to f64")
+            * x.inner.bits() as f64)
+            .floor()
+            + 1f64;
```
Comment (RageKnify) [inline boa/src/bigint.rs:175]: Could you change the order of the operation? I was a bit confused reading `y * x.bits`, I'd say `x.bits * y` is more natural since we're thinking of `x^y`.

**Review by RageKnify — CHANGES_REQUESTED** [review]
Minor suggestion for readability, but it might make it look weird. Not sure about the test, don't see how it can possibly be affected.

**Review by RageKnify — APPROVED** [review]

**Review by HalidOdat — APPROVED** [review]
