### PR TITLE
Fix enumerable attribute on array length property

### LINKED ISSUE #971: The `length` property of an array is enumerable
**Describe the bug**
The `length` property of an array is enumerable, but it should not.

**To Reproduce**
This JavaScript code reproduces the issue:
```javascript
>> [].propertyIsEnumerable("length")
true
```

**Expected behavior**
`[].propertyIsEnumerable("length")` should be `false`.

**Build environment**

- OS: Windows 10
- Version: 0.10
- Target triple: x86_64-pc-windows-msvc
- Rustc version: rustc 1.48.0 (7eac88abb 2020-11-16)

**Additional context**
None

### PR DESCRIPTION
**Pull request by tofpie**
This Pull Request fixes #971 .

It changes the following:

- The `length` property of an array is set to non enumerable

### CODE REVIEW

**Review by RageKnify — APPROVED** [review]

**Comment by Razican** [comment]
Does this fix both cases?
```javascript
>> Array.prototype.propertyIsEnumerable("length")
false
>> [].propertyIsEnumerable("length")
false
```

### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,460 | 78,460 | 0 |
  | Passed | 19,374 | 19,378 | **+4** |
  | Ignored | 15,559 | 15,559 | 0 |
  | Failed | 43,527 | 43,523 | **-4** |
  | Panics | 465 | 465 | 0 |
  | Conformance | 24.69 | 24.70 | **+0.01%** |

**Review by Razican — APPROVED** [review]
Looks good to me! :) thanks

**Comment by tofpie** [comment]
Not yet, I will add the fix for `Array.prototype`

**Comment by Razican** [comment]
> Not yet, I will add the fix for `Array.prototype`

Yes, please :) that way we fix both

File: boa/src/builtins/array/mod.rs [hunk 1]
```diff
@@ -58,7 +58,7 @@ impl BuiltIn for Array {
         )
         .name(Self::NAME)
         .length(Self::LENGTH)
-        .property("length", 0, Attribute::all())
+        .property("length", 0, Attribute::WRITABLE | Attribute::NON_ENUMERABLE)
```
Comment (Razican) [inline boa/src/builtins/array/mod.rs:61]: I would add `Attribute::PERMANENT` too, to make it more explicit, even if it's the same.

**Comment by Razican** [comment]
This is blocked on #977.

**Comment by Razican** [comment]
#977 was merged, could you rebase?
