### PR TITLE
JSON.stringify(undefined) should return undefined

### LINKED ISSUE #509: [JSON] JSON.stringify(undefined) panics
In Chrome it returns "undefined".

But in the spec https://tc39.es/ecma262/#sec-json.stringify it says:
image

In boa it panics:
```
thread 'main' panicked at 'internal error: entered unreachable code: Symbols and Undefined JSON Values depend on parent type', boa/src/builtins/value/mod.rs:264:17
```

### PR DESCRIPTION
**Pull request by n14little**
This Pull Request fixes/closes #509

It changes the following:
 - `JSON.stringify(undefined);` now returns undefined according to [spec](https://tc39.es/ecma262/#sec-json.stringify)

### CODE REVIEW

File: boa/src/builtins/json/tests.rs [hunk 1]
```diff
@@ -191,11 +191,13 @@ fn json_stringify_return_undefined() {
     let actual_no_args = forward(&mut engine, r#"JSON.stringify()"#);
     let actual_function = forward(&mut engine, r#"JSON.stringify(() => {})"#);
     let actual_symbol = forward(&mut engine, r#"JSON.stringify(Symbol())"#);
+    let actual_undefined = forward(&mut engine, r#"JSON.stringify(undefined)"#);
     let expected = forward(&mut engine, r#"undefined"#);
 
     assert_eq!(actual_no_args, expected);
     assert_eq!(actual_function, expected);
     assert_eq!(actual_symbol, expected);
+    assert_eq!(actual_undefined, expected);
```
Comment (HalidOdat) [inline boa/src/builtins/json/tests.rs:200]: Maybe we should separate the tests, instead of them all being in one test.

Comment (n14little) [reply boa/src/builtins/json/tests.rs]: :heavy_check_mark:
