### PR TITLE
Adjust `EnumerableOwnPropertyNames` to use all `String` type property keys

### LINKED ISSUE #1501: `Object.keys` does not work with index property keys
**Describe the bug**
`Object.keys` does not work with index property keys

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.

This JavaScript code reproduces the issue:
```javascript
let o = [1, 2, 3];
Object.keys(o);
```
The output is `[]`

**Expected behavior**
The output should be `[ '0', '1', '2' ]`

**Build environment:**

- OS: Linux
- Version: eaaae8544
- Target triple:x86_64-unknown-linux-gnu
- Rustc version: rustc 1.53.0 (53cb7b09b 2021-06-17)

### PR DESCRIPTION
**Pull request by raskad**
This Pull Request fixes/closes #1501.

It changes the following:

- Adjust `EnumerableOwnPropertyNames` to use all `String` type property keys

This looks different from the [spec](https://tc39.es/ecma262/#sec-enumerableownpropertynames), because the meaning of `String` in `4.a: If Type(key) is String, then` is different than our internal `PropertyKey` enum types `String`, `Symbol` and `Index`. Our internal `Index` type is a `String` type in the context of the spec.
This PR is only a fix for this specific function. We should change our `[[OwnPropertyKeys]]` to be spec compliant, but I think we should wait with that until #1354 is merged, because `[[OwnPropertyKeys]]` is defined multiple times for different object types.

### CODE REVIEW

**Comment by raskad** [comment]
The broken test is actually broken and should not have passed before ;)

### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 31,283 | 31,287 | **+4** |
  | Ignored | 15,612 | 15,612 | 0 |
  | Failed | 32,002 | 31,998 | **-4** |
  | Panics | 2 | 2 | 0 |
  | Conformance | 39.65% | 39.66% | **+0.01%** |
  
  <details><summary><b>Fixed tests:</b></summary>
  
  ```
  test/built-ins/Object/keys/15.2.3.14-5-14.js [strict mode] (previously Failed)
  test/built-ins/Object/keys/15.2.3.14-5-14.js (previously Failed)
  test/built-ins/Object/keys/15.2.3.14-3-4.js [strict mode] (previously Failed)
  test/built-ins/Object/keys/15.2.3.14-3-4.js (previously Failed)
  test/built-ins/Object/keys/15.2.3.14-3-3.js [strict mode] (previously Failed)
  test/built-ins/Object/keys/15.2.3.14-3-3.js (previously Failed)
  ```
  </details>
  
  <details><summary><b>Broken tests:</b></summary>
  
  ```
  test/built-ins/Object/keys/15.2.3.14-5-11.js [strict mode] (previously Passed)
  test/built-ins/Object/keys/15.2.3.14-5-11.js (previously Passed)
  ```
  </details>

**Review by HalidOdat — APPROVED** [review]

File: boa/src/object/internal_methods.rs [hunk 1]
```diff
@@ -902,15 +902,23 @@ impl GcObject {
...
         for key in own_keys {
             // a. If Type(key) is String, then
-            if let PropertyKey::String(key_str) = &key {
+            let key_str = if let PropertyKey::Index(index) = &key {
+                Some(index.to_string().into())
+            } else if let PropertyKey::String(key_str) = &key {
+                Some(key_str.clone())
+            } else {
+                None
+            };
```
Comment (HalidOdat) [inline boa/src/object/internal_methods.rs:911]:
```suggestion
            let key_str = if let PropertyKey::Index(index) = &key {
                Some(index.to_string().into())
            } else if let PropertyKey::String(key_str) = &key {
                Some(key_str.clone())
            } else {
                None
            };
```
I think a `match` here would make it more readable :)

File: boa/src/object/internal_methods.rs [hunk 2]
```diff
@@ -902,15 +902,23 @@ impl GcObject {
...
+
+            if let Some(key_str) = key_str {
                 // i. Let desc be ? O.[[GetOwnProperty]](key).
                 let desc = self.__get_own_property__(&key);
                 // ii. If desc is not undefined and desc.[[Enumerable]] is true, then
                 if let Some(desc) = desc {
                     if desc.expect_enumerable() {
                         // 1. If kind is key, append key to properties.
                         if let PropertyNameKind::Key = kind {
```
Comment (HalidOdat) [inline boa/src/object/internal_methods.rs:920]: We could also match on `PropertyNameKind` too

File: boa/src/object/internal_methods.rs (hunk 1 above)
Comment (raskad) [reply boa/src/object/internal_methods.rs]: True, looks way better.

File: boa/src/object/internal_methods.rs (hunk 2 above)
Comment (raskad) [reply boa/src/object/internal_methods.rs]: Changed that in bb25549

**Review by HalidOdat — APPROVED** [review]

**Review by Razican — APPROVED** [review]
Looks very good, nice catch!
