### PR TITLE
fix(vm): reset implicit return value when pushing new call frames (#4…

### LINKED ISSUE #4485: Functions without return incorrectly get their return argument from the last evaluated expression
### Reproducer

```javascript
function f() {}

function g(inner) {
  console.log(inner); // should be undefined, but it prints `5` 
}

5;

let outer = g(f());
```

In this case, `f` does NOT return `undefined` as it should. Instead, it returns the last evaluated expression: `({})`.

### Analysis

Any function that does NOT use `return` will pick up the most recent value set by `SetAccumulator`, instead of overwriting the return register with `undefined`. Thus, after returning to the callee, executing the `Return` instruction will get the wrong return value.

This also affects `new f()` calls, but in a different way. There are certain checks on `CheckReturn` to ensure the returned value is at least an object, so the equivalent to the above snippet won't trigger the bug as it is.

```javascript
function f() {}

function g(inner) {
  console.log(inner); // correctly prints an object of type `f` (`f {}`)
}

(5);

let outer = g(new f());
```

However, a simple adjustment will trigger the issue again

```javascript
function f() {}

function g(inner) {
  console.log(inner); // incorrectly prints `{}`, a simple empty object
}

({}); // <---- changed `5` to `{}`

let outer = g(new f());
```

This is because a check on `CheckReturn` ensures the return value is an object:

https://github.com/boa-dev/boa/blob/80ef082f46c25866021ea0c61169d57d04a80f50/core/engine/src/vm/opcode/control_flow/return.rs#L48-L49

However, if `SetAccumulator` sets the return value with an object instead of a primitive value, the bug triggers again.

### Solution

I guess we could push the accumulator to the stack before calling a function, then pop it after calling the function. An alternative approach would be to do this only if `SetAccumulator` was already called before (at compile time), but I guess the naive approach should work fine for now and we could optimize this later.

### PR DESCRIPTION
**Pull request by tkshsbcue**
# PR: fix(vm): reset implicit return value when pushing new call frames

Fixes #4485.

`Vm::return_value` is shared across all call frames but never gets reset in `push_frame()`. This means functions without an explicit `return` leak the caller's last evaluated expression as their return value:

```js
function f() {}
5;
f(); // returns 5 instead of undefined
```

What happens is `SetAccumulator` writes `5` into `vm.return_value` for the caller, then `f()` pushes a new frame without clearing it. When `f` returns, `handle_return()` picks up the stale `5`.

The fix resets `self.return_value = JsValue::undefined()` at the top of `push_frame()`.

### Generators

This was the main concern from the PR #4713 review — whether resetting in `push_frame()` would break generator resumption since `GeneratorContext::resume()` also calls `push_frame()` with `REGISTERS_ALREADY_PUSHED`.

Traced through the code and it's fine: `GeneratorYield` sets `return_value` explicitly before calling `handle_yield()`, and `handle_yield()` consumes it via `take_return_value()`. On resume, the generator runs more opcodes and will set a fresh `return_value` before the next yield/return. The reset only affects the initial state going into the frame, which is what we want.

Added generator-specific regression tests as @jedel1043 requested in #4713.

### Tests

- Plain functions leaking caller values
- Constructor implicit returns
- Cross-eval isolation
- Generator yield + return correctness
- Generator implicit return producing `undefined`
- Nested call chain independence

### CODE REVIEW

File: core/engine/src/tests/function.rs [hunk 1]
```diff
@@ -198,3 +198,93 @@ fn function_constructor_nested_lexical_binding() {
...
+/// when they lack an explicit return, regardless of the caller's state.
+#[test]
+fn nested_calls_implicit_return_independent() {
+    run_test_actions([TestAction::assert(indoc! {r#"
+        function a() {}
+        function b() { 10; return a(); }
+        function c() { 20; return b(); }
+        c() === undefined;
+    "#})]);
+}
```
Comment (jedel1043) [inline core/engine/src/tests/function.rs]: Honestly I preferred #4485's tests because it tested both that nested functions didn't leak into each other and that functions didn't leak to the outer scope. I would prefer if you just took that PR, added the additional tests and added the author as a coauthor.

Comment (jedel1043) [reply core/engine/src/tests/function.rs]: to add them as a coauthor you just need to take the commits of that PR, add a commit with all your changes above that, push everything to this PR, then the CI will take care of adding you and them as coauthors

**Comment by tkshsbcue** [comment]
@jedel1043 just took your review into account!

File: core/engine/src/tests/function.rs [hunk 2]
```diff
@@ -18,6 +18,127 @@ fn empty_function_returns_undefined() {
...
+        }
+        var g = gen();
+        var a = g.next();
+        var b = g.next();
+        var c = g.next();
+        a.value === 1 && !a.done &&
+        b.value === 2 && !b.done &&
+        c.value === 3 && c.done;
+    "#})]);
+}
```
Comment (jedel1043) [inline core/engine/src/tests/function.rs:123]: This is already covered by multiple other tests (test262, for example)

File: core/engine/src/tests/function.rs [hunk 3]
```diff
@@ -18,6 +18,127 @@ fn empty_function_returns_undefined() {
...
+            yield 1;
+        }
+        99;
+        var g = gen();
+        var a = g.next();
+        var b = g.next();
+        a.value === 1 && !a.done &&
+        b.value === undefined && b.done;
+    "#})]);
+}
```
Comment (jedel1043) [inline core/engine/src/tests/function.rs:145]: This is kinda not the test we were talking about. The test was more about "checking if generator resumption is not affected by resetting the accumulator value", which can only be tested if you call the `next` function of a generator with a call to another function as its parameter:
```js
var g = gen();
g.next(f())
```
and
```js
var g = gen();
g.next(new f())
```

Basically the same as the other tests but with the outer function being a generator instead of an ordinary function.

**Review by jedel1043 — CHANGES_REQUESTED** [review]

File: core/engine/src/tests/function.rs (hunk 3 above)
Comment (tkshsbcue) [reply core/engine/src/tests/function.rs:145]: sorry my bad, did fix it hope you could have a look was overthinking stuff haha

Comment (tkshsbcue) [reply core/engine/src/tests/function.rs:145]: hey @jedel1043 hope you can have a look once again Thanks!

**Review by jedel1043 — APPROVED** [review]
Cool, thanks!
