### PR TITLE
Fix/headers iterable #4611

### LINKED ISSUE #4611: Headers should be iterable
```console
% boa
>> [...new Headers([['x','y']])]
Uncaught: TypeError: value with type `object` is not iterable (native at core/engine/src/builtins/iterable/mod.rs:307:13)
    at <main> (unknown at :?:?)
>> new Map(new Headers([['x','y']]))
Uncaught: TypeError: value with type `object` is not iterable (native at core/engine/src/builtins/iterable/mod.rs:307:13)
    at <main> (unknown at :1:1)
```

```console
% node
> [...new Headers([['x','y']])]
[ [ 'x', 'y' ] ]
> new Map(new Headers([['x','y']]))
Map(1) { 'x' => 'y' }
```

### PR DESCRIPTION
**Pull request by Rahul-2k4**
## Summary

  This PR makes `Headers` iterable in Boa runtime so it can be consumed by iterable APIs.

This Pull Request closes #4611 

  ### What changed

  - Added a regression test for `Headers` iterability:
    - spread: `[...new Headers([["x", "y"]])]`
    - `Map` construction: `new Map(new Headers([["x", "y"]]))`
  - Wired `Headers.prototype[Symbol.iterator]` during fetch registration.
  - Exposed `entries`, `keys`, and `values` as class methods on `Headers`.

  ### Why

  `Headers` should be iterable over `[name, value]` pairs. Without `@@iterator`, spread and
  `Map` construction throw a `TypeError`.

  ## Testing

  ```bash
  cargo test -p boa_runtime fetch::tests -- --nocapture

  All fetch tests pass, including the new regression test.

### CODE REVIEW

File: core/runtime/src/fetch/headers.rs [hunk 1]
```diff
@@ -244,6 +245,7 @@ impl JsHeaders {
     /// Returns an iterator allowing you to go through all keys of the key/value pairs
     /// contained in this object.
     #[allow(clippy::unused_self)]
+    #[boa(method)]
```
Comment (jedel1043) [inline core/runtime/src/fetch/headers.rs]: Why add the `method` attribute? If the function starts with `&self`, it will automatically be exposed as a method.

Comment (Rahul-2k4) [reply core/runtime/src/fetch/headers.rs]: Yep  right, &self methods are already exposed auto, so [boa(method)] is redundant . I will remove the extra attribute from`keys values .entries.

**Comment by jedel1043** [comment]
If you're using AI agents to do this work, maybe you should use something like [git-worktree](https://git-scm.com/docs/git-worktree) to avoid accidentally pushing unrelated commits? Just a suggestion.

**Comment by Rahul-2k4** [comment]
yep sure @jedel1043 ill keep that in mind . i got little confused because of some uncommited changes of my other pr . and again thank you for the suggestion of worktree that it will keep my workspace clean . Will keep in mind and ill surely improve from next time and thanks for the quick reviews

File: core/runtime/src/fetch/headers.rs (hunk 1 above)
Comment (jedel1043) [reply core/runtime/src/fetch/headers.rs]: uhhh so? nothing changed...

Comment (Rahul-2k4) [reply core/runtime/src/fetch/headers.rs]: my appologies , now i have correctly implemented on suggestion for the removal of redundant #[boa(method)] from entries/keys/values in core/runtime/src/fetch/headers.rs at [commit](https://github.com/boa-dev/boa/pull/4638/commits/ac29992edb8e0fe3e5140616b81a19f5bfde9706)

File: core/runtime/src/fetch/mod.rs [hunk 2]
```diff
@@ -191,7 +212,33 @@ pub fn register<F: Fetcher>(
...
+
+    headers_proto.define_property_or_throw(
+        JsSymbol::iterator(),
+        PropertyDescriptor::builder()
+            .value(iterator)
+            .writable(true)
+            .enumerable(false)
+            .configurable(true),
+        context,
+    )?;
```
Comment (jedel1043) [inline core/runtime/src/fetch/mod.rs:239]: Oof, seems kind of ugly having to do all of this just to add a symbol method. Can you open an issue about adding support for symbols in the `#[boa(class)]` macro, then add a TODO here to change it later?

Comment (Rahul-2k4) [reply core/runtime/src/fetch/mod.rs:239]: ok i have raised an issue for the same

File: core/runtime/src/fetch/mod.rs [hunk 3]
```diff
@@ -176,6 +178,25 @@ pub mod js_module {
...
+        })?;
+
+    let entries = headers.entries(context);
+    let entries_obj = entries.to_object(context)?;
+    let method = entries_obj
+        .get(JsSymbol::iterator(), context)?
+        .as_object()
+        .ok_or_else(|| js_error!(TypeError: "entries result is not iterable"))?;
+
+    method.call(&entries, &[], context)
```
Comment (jedel1043) [inline core/runtime/src/fetch/mod.rs]: I think here you should be able to wrap `headers.entries(context)` with a `JsArray` then call `values` IIRC. That should avoid having to do this dance of manually fetching the iterator method.

Comment (Rahul-2k4) [reply core/runtime/src/fetch/mod.rs]: Hmmmm I think that's much better approach. Nice , will resolve this now

**Review by jedel1043 — APPROVED** [review]
Looks great! We'll hopefully remove all the boilerplate of setting up the method symbol when #4697 gets merged.

**Comment by Rahul-2k4** [comment]
@jedel1043 yep sure
