### PR TITLE
Deny Unicode Escapes in boolean and null expressions

### LINKED ISSUE #2771: Keywords with Unicode escapes should throw syntax errors
**Describe the bug**
Currently, if we use a keyword with an Unicode escape, it will just work, and interpret it as the keyword itself. This is a follow-up from #1117.

**To Reproduce**
The following JavaScript code reproduces the issue:

```javascript
let x = f\u{61}lse;
```

**Expected behavior**
This should throw a syntax error. Instead, it just assigns the `false` boolean value to the `x` variable.

### PR DESCRIPTION
**Pull request by veera-sivarajan**
This Pull Request fixes/closes #2771.

This PR keeps track of `ContainsEscapeSequence` in all `TokenKind::BooleanLiteral` and `TokenKind::NullLiteral` and throws an error when it gets parsed as an expression.

Opening a different PR for this since I messed up the commit history of the previous PR.

### CODE REVIEW

**Comment by HalidOdat** [comment]
| Test result | main count | PR count | difference |
| :---------: | :----------: | :------: | :--------: |
| Total | 94,657 | 94,657 | 0 |
| Passed | 73,901 | 73,901 | 0 |
| Ignored | 17,505 | 17,505 | 0 |
| Failed | 3,251 | 3,251 | 0 |
| Panics | 0 | 0 | 0 |
| Conformance | 78.07% | 78.07% | 0.00% |

**Comment by raskad** [comment]
Since there seems to be not explicit test for this in the 262 suite, could you add some tests for this that make sure the parser produces syntax errors in these cases?

File: boa_parser/src/lexer/token.rs [hunk 1]
```diff
@@ -95,7 +95,7 @@ impl From<BigInt> for Numeric {
 #[derive(Clone, PartialEq, Debug)]
 pub enum TokenKind {
     /// A boolean literal, which is either `true` or `false`.
-    BooleanLiteral(bool),
+    BooleanLiteral((bool, ContainsEscapeSequence)),
```
Comment (HalidOdat) [inline boa_parser/src/lexer/token.rs:98]:
```suggestion
    BooleanLiteral(bool),
```

I think it's best to leave it as is, and throw the error when we create the `TokenKind::BooleanLiteral` (same for `TokenKind::NullLiteral`), since a boolean and null literal shouldn't have escape sequence.

**Review by HalidOdat — COMMENTED** [review]
Looks good, check my comment to see on how we might improve this :)

File: boa_parser/src/lexer/token.rs (hunk 1 above)
Comment (veera-sivarajan) [reply boa_parser/src/lexer/token.rs:98]: Thanks for the suggestion.

But, if I throw an error when `Token::BooleanLiteral` is created at `boa_parser/src/lexer/identifier.rs`, it will reject the following code too:
```
let o = { f\u{61}lse: 10}; // should work
o.f\u{61}lse
```

Shouldn't we throw an error only when a `TokenKind::BooleanLiteral` or `TokenKind::NullLiteral` is parsed as a literal?

Comment (HalidOdat) [reply boa_parser/src/lexer/token.rs:98]: ah, I see, You are right! Forgot about those cases :sweat_smile:

**Review by HalidOdat — APPROVED** [review]
Thanks for the contribution! @veera-sivarajan Looks perfect to me! :)

**Comment by Razican** [comment]
> Since there seems to be not explicit test for this in the 262 suite, could you add some tests for this that make sure the parser produces syntax errors in these cases? 

Should we try to add such a test to Test262, or report it at least?

**Comment by veera-sivarajan** [comment]
> > Since there seems to be not explicit test for this in the 262 suite, could you add some tests for this that make sure the parser produces syntax errors in these cases?
> 
> Should we try to add such a test to Test262, or report it at least?

I have opened a [PR](https://github.com/tc39/test262/pull/3831) for the same.

**Review by raskad — APPROVED** [review]
Really nice job, great contribution!
