### PR TITLE
docs: Fix link to examples

### LINKED ISSUE #4006: Link to `examples` is broken in boa_engine
The link to `examples` is broken in boa_engine

### PR DESCRIPTION
**Pull request by it-a-me**
This Pull Request fixes/closes #4006

### CODE REVIEW

File: core/engine/src/lib.rs [hunk 1]
```diff
@@ -3,7 +3,7 @@
 //!
 //! # Example usage
 //!
-//! You can find multiple examples of the usage of Boa in the [`boa_examples`][examples] crate. In
```
Comment (HalidOdat) [inline core/engine/src/lib.rs:6]: I think the name of the crate was correct because the crate is called `boa_examples` as can be seen in the [examples/Cargo.toml](https://github.com/boa-dev/boa/blob/main/examples/Cargo.toml#L2).

**Review by HalidOdat — COMMENTED** [review]
Besides the comment this looks good to me! :)

**Comment by it-a-me** [comment]
It should be fixed now.  I was just looking at the directory name rather than the crate name, mb

**Review by jedel1043 — APPROVED** [review]
Thank you!

**Review by HalidOdat — APPROVED** [review]
Looks good to me! :)
