### PR TITLE
Fixed function call with unspecified arguments

### LINKED ISSUE #505: Unreachable statement
**Describe the bug**
First of all, I'd just like to say this project is really exciting, I can't wait to see it reach a usable state :)

So, I tried the online version and wrote a few functions that worked correctly, but then tried to run a simple Fibonacci function and got the following error in the console:

```
VM1040 errors.js:22 Uncaught Error: unreachable

RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h5395f3796c27894a (/boa/fefc83080ce6a9a22427.module.wasm:wasm-function[4079]:0x36d471)
    at rust_begin_unwind (/boa/fefc83080ce6a9a22427.module.wasm:wasm-function[13868]:0x46f89f)
    at core::panicking::panic_fmt::h0dbc4ba05c77baa3 (/boa/fefc83080ce6a9a22427.module.wasm:wasm-function[16179]:0x48dc02)
    at core::option::expect_failed::h6d3422f1d95e4ebe (/boa/fefc83080ce6a9a22427.module.wasm:wasm-function[9677]:0x425c3c)
    at core::option::Option<T>::expect::h47516ce156c1e24c (/boa/fefc83080ce6a9a22427.module.wasm:wasm-function[7360]:0x3ec249)
    at boa::builtins::function::Function::call::h4fe28ddf1172dfd6 (/boa/fefc83080ce6a9a22427.module.wasm:wasm-function[399]:0x1e2d75)
    at boa::exec::Interpreter::call::hd8f2baa22109a189 (/boa/fefc83080ce6a9a22427.module.wasm:wasm-function[1443]:0x2a7d9a)
    at <boa::exec::Interpreter as boa::exec::Executor>::run::h605b729b83560642 (/boa/fefc83080ce6a9a22427.module.wasm:wasm-function[7]:0x9593f)
    at <boa::exec::Interpreter as boa::exec::Executor>::run::h605b729b83560642 (/boa/fefc83080ce6a9a22427.module.wasm:wasm-function[7]:0x8beb6)
    at boa_wasm::evaluate::h75b1399c0202d4b7 (/boa/fefc83080ce6a9a22427.module.wasm:wasm-function[199]:0x18993b)
    at eval (VM1040 errors.js:22)
```

**To Reproduce**
Here is the source code:

```js
function fibonacci(num, memo) {
  memo = memo || {};

  if (memo[num]) return memo[num];
  if (num <= 1) return 1;

  return memo[num] = fibonacci(num - 1, memo) + fibonacci(num - 2, memo);
}

fibonacci(1)
```

**Expected behavior**
The code should compile and display `1`.

**Build environment (please complete the following information):**
 - OS: Windows 10
 - Version: x64 ; May 2020 Update
 - Target triple: online demo (https://boa-dev.github.io/boa/)
 - Rustc version: online demo

### PR DESCRIPTION
**Pull request by HalidOdat**
This pull request fixes #505 

It changes the following:
 - Fixed calling a function with less amount of arguments than the function declaration parameters.

This is blocked until #501 lands

### CODE REVIEW

File: boa/src/exec/tests.rs [hunk 1]
```diff
@@ -912,3 +912,23 @@ fn to_string() {
     assert_eq!(engine.to_string(&Value::rational(55.0)).unwrap(), "55");
     assert_eq!(engine.to_string(&Value::string("hello")).unwrap(), "hello");
 }
+
+#[test]
+fn calling_function_with_unspecified_arguments() {
+    let realm = Realm::create();
+    let mut engine = Interpreter::new(realm);
+    let scenario = r#"
+        function fibonacci(num, memo) {
```
Comment (pedropaulosuzuki) [inline boa/src/exec/tests.rs:921]: I think this test is too broad. We are not only checking to see the behaviour of unspecified arguments, but also array access, || operator, recursion and more. Maybe we should do a check with a simpler method, such as
```js
function test(a, b) {
    return b;
}

test(10)
```
``` assert_eq!(foward(&mut engine, scenario), "undefined"); ```

Or something similar.

Comment (HalidOdat) [reply boa/src/exec/tests.rs:921]: Yes. this is probably the best option. I just took the code that was broken from the issue as the test.
