### PR TITLE
Set __proto__ of function instances

### LINKED ISSUE #531: [builtins] Builtin function doesnt have constructor property
**To Reproduce**
`[].findIndex.constructor` 

**Expected behavior**
Should return a `Function` constructor. Instead `undefined` is returned.

Custom functions do have `constructor` property which returns correctly.

### PR DESCRIPTION
**Pull request by 54k1**
This Pull Request fixes/closes #531 

It changes the following:
- make_builtin_fn now takes &Interpreter as an argument.
- Call sites are updated according to the new function signature of make_builtin_fn

### CODE REVIEW

File: boa/src/builtins/function/mod.rs [hunk 1]
```diff
@@ -513,15 +513,27 @@ pub fn make_constructor_fn(
...
     let _timer = BoaProfiler::global().start_event(&format!("make_builtin_fn: {}", &name), "init");
 
     // FIXME: function needs the Function prototype set.
     let mut function = Object::function(Function::builtin(Vec::new(), function), Value::null());
+    function.set_prototype(
+        interpreter
+            .global()
+            .get_field("Function")
+            .get_field("prototype"),
+    );
```
Comment (HalidOdat) [inline boa/src/builtins/function/mod.rs:535]: We can remove the `set_prototype` call, instead we initialize it in the `Object::function()` since it takes the function and the prototype we can pass it instead of `Value::null()`

Also we can now remove the `FIXME` comment since we fixed the issue.

Comment (54k1) [reply boa/src/builtins/function/mod.rs]: Thanks for the review.

File: boa/src/builtins/function/mod.rs [hunk 2]
```diff
@@ -513,15 +513,26 @@ pub fn make_constructor_fn(
...
     let _timer = BoaProfiler::global().start_event(&format!("make_builtin_fn: {}", &name), "init");
 
-    // FIXME: function needs the Function prototype set.
-    let mut function = Object::function(Function::builtin(Vec::new(), function), Value::null());
+    let mut function = Object::function(
+        Function::builtin(Vec::new(), function),
+        interpreter
+            .global()
+            .get_field("Function")
+            .get_field("prototype"),
```
Comment (Razican) [inline boa/src/builtins/function/mod.rs:533]: I'm not super up to date with this, but isn't this similar to the `prototype()` function?

https://github.com/boa-dev/boa/blob/8fd5533460af8c0c424f6ddf4f3d45ed84815f8f/boa/src/builtins/object/mod.rs#L432

Comment (54k1) [reply boa/src/builtins/function/mod.rs:533]: Yes, it looks like the final `get_field` does the same thing as the `prototype()` function.
Thanks for your comment.

Comment (HalidOdat) [reply boa/src/builtins/function/mod.rs:533]: > I'm not super up to date with this, but isn't this similar to the `prototype()` function?

Its not the same. the `.prototype()` function does not return the `prototype` it returns the prototype instance so for `Function` it would be `Object.prototype`, not `Function.protoype`

It is confusing, it should be called `prototype_instance()` or something like that, since that is what is does

Comment (HalidOdat) [reply boa/src/builtins/function/mod.rs:533]: Created an issue about the naming of `prototype` #607

Comment (54k1) [reply boa/src/builtins/function/mod.rs:533]: > for `Function` object it would be `Object.prototype`, not `Function.protoype`

Shouldn't `Function.__proto__ === Function.prototype`?

Comment (HalidOdat) [reply boa/src/builtins/function/mod.rs:533]: > Shouldn't `Function.__proto__ === Function.prototype`?

Actually you are right, sorry about that :sweat_smile: , the `Function` object has the `__proto__` set to `Function.prototype` since it is a function and it inherits from it self (`Function`). so in this case it would be the same.
Screenshot_2020-08-07_18-48-30

Comment (54k1) [reply boa/src/builtins/function/mod.rs:533]: This turns out to be a 'special case'. :)

Comment (54k1) [reply boa/src/builtins/function/mod.rs:533]: Since @HalidOdat mentioned about updating parts of the code to cache frequently used objects such as `Function`, `Object`, etc. can we leave it this way for now?

Comment (HalidOdat) [reply boa/src/builtins/function/mod.rs:533]: > Since @HalidOdat mentioned about updating parts of the code to cache frequently used objects such as `Function`, `Object`, etc. can we leave it this way for now?

Yes. I was just suggesting a possible optimization that we can do in the future.
