### PR TITLE
Arrow parse

### LINKED ISSUE #1032: Arrow Function Parsing fails
**ECMASCript feature**
ES6 Arrow functions

**Example code**
Give a code example that should work after the implementation of this feature.

This code should now work and give the expected result:
```javascript
let a = "Hello";
let thing = (b) => a + b;
thing(" World!");
```
The expected output is `Hello World!`.

### PR DESCRIPTION
**Pull request by Lan2u**
Fixes #1032 
Fixes a bug in arrow function parsing which prevented the assignment of arrow functions with a single argument using parentheses (e.g. `let foo = (a) => a` )

Arrow functions with > 1 argument or arrow functions that don't use parentheses already parse correctly

### CODE REVIEW

File: boa/src/syntax/parser/expression/assignment/arrow_function.rs [hunk 1]
```diff
@@ -71,7 +71,12 @@ where
     fn parse(self, cursor: &mut Cursor<R>) -> Result<Self::Output, ParseError> {
         let _timer = BoaProfiler::global().start_event("ArrowFunction", "Parsing");
 
+        println!("Parsing arrow func");
+
         let next_token = cursor.peek(0)?.ok_or(ParseError::AbruptEnd)?;
+
+        println!("Next token {}", next_token);
+
```
Comment (Razican) [inline boa/src/syntax/parser/expression/assignment/arrow_function.rs:79]: It seems there are some debugging statements left.

**Review by Razican — APPROVED** [review]
Looks very good, thanks! Could we add also a test to check for 3 arguments? Just in case.

Also a couple of prints left.

File: boa/src/syntax/parser/expression/assignment/arrow_function.rs (hunk 1 above)
Comment (Lan2u) [reply boa/src/syntax/parser/expression/assignment/arrow_function.rs]: Ah yes - removed

**Review by RageKnify — APPROVED** [review]

**Review by tofpie — APPROVED** [review]
