### PR TITLE
`ConstructorBuilder`, `ObjectInitializer`, cache standard objects and fix global object attributes

### LINKED ISSUE #613: Cache standard objects (`Array`, `Object`, etc) and there prototypes
**What is the problem with the current implementation?**
The problem is that when we access a standard object we use `.get_field()` to get it from the global object, the problem is that we have to do a hashmap lookup and `.get_field()` does other checks that are not necessary.

we have to do:
```rust
interpreter.global().get_field("Object")
```
or to get the prototype we have to do two HashMap lookups
```rust
interpreter.global().get_field("Object").get_field("prototype")
```

**Proposed changes**
Store the common standard objects in the realm/interpreter as struct fields maybe:
```rust
struct StandardObject {
	object: GcObject,
	prototype: GcObject,
}
struct StandardObjects {
	object_object: StandardObject,
	array_object: StandardObject,
	function_object: StandardObject,
	error_object: StandardObject,
	// ... other standard objects ...
}
```
This way if we need to access the prototype of for example `Function` object we do something like:
```rust
interpreter.standard_objects.function_object.prototype
```
This way we avoid all the unnecessary `HashMap` lookups and the checks from `.get_field()`

### PR DESCRIPTION
**Pull request by HalidOdat**
This Pull Request fixes/closes #613.

It changes the following:
 - Add BuiltIn trait for builtins
 - Fixed global properties/objects/object methods/object properties attributes
 - Made `ClassBuilder` retun `&mut Self`
 - Add ConstructorBuilder for constructing constructors (builder pattern)
 - Add ObjectInitializer for constructing objects (builder pattern) 
 - Add FunctionBuilder for constructing function objects (builder pattern) 
 - Cache core standard objects

### CODE REVIEW

**Comment by HalidOdat** [comment]
This is ready for review/merge :)

Created some issues to track what was been fixed/improved, and looking at how many there are... maybe I overdid it :sweat_smile:

File: boa/src/object/internal_methods.rs [hunk 1]
```diff
@@ -336,7 +336,7 @@ impl Object {
 
     /// Helper function for property insertion.
     #[inline]
-    pub(crate) fn insert_property<K>(&mut self, key: K, property: Property) -> Option<Property>
+    pub(crate) fn insert<K>(&mut self, key: K, property: Property) -> Option<Property>
```
Comment (RageKnify) [inline boa/src/object/internal_methods.rs:339]: `Object::insert`  inserts a `Property`, but `Object::insert_property`, inserts `V: Into<Value>`.
Seems pretty confusing to me, should switch them up, no?

File: boa/src/context.rs [hunk 2]
```diff
@@ -27,11 +27,130 @@ use crate::{
...
+}
+
 /// Javascript context. It is the primary way to interact with the runtime.
 ///
-/// For each `Context` instance a new instance of runtime is created.
-/// It means that it is safe to use different contexts in different threads,
-/// but each `Context` instance must be used only from a single thread.
+/// `Context`s constructed in a thread share the same runtime, therefore it
+/// is possible to share objects from one context to another context, but they
+/// have to in the same thread.
```
Comment (RageKnify) [inline boa/src/context.rs:153]: \*have to ***be*** in the same thread.

File: boa/src/class.rs [hunk 3]
```diff
@@ -108,157 +107,81 @@ impl<T: Class> ClassConstructor for T {
...
-                .get_field("prototype"),
-        );
-
-        function.insert_field("length", Value::from(length));
-        function.insert_field("name", Value::from(name.as_str()));
-
-        self.prototype
-            .borrow_mut()
-            .insert_field(name, Value::from(function));
+        // TODO: \/
```
Comment (RageKnify) [inline boa/src/class.rs:135]: Can you detail the `TODO` or was it from when you were implementing it?

File: boa/src/builtins/map/mod.rs [hunk 4]
```diff
@@ -15,11 +15,92 @@ mod tests;
...
+    /// Create a new map
+    pub(crate) fn constructor(this: &Value, args: &[Value], ctx: &mut Context) -> Result<Value> {
+        // Make a new Object which will internally represent the Array (mapping
+        // between indices and values): this creates an Object with no prototype
+
+        // Set Prototype
+        let prototype = ctx.global_object().get_field("Map").get_field(PROTOTYPE);
+
+        this.as_object_mut()
+            .expect("this is array object")
```
Comment (RageKnify) [inline boa/src/builtins/map/mod.rs:56]: Should be `"this is map object"`, right?

File: boa/src/builtins/error/type.rs [hunk 5]
```diff
@@ -16,24 +16,50 @@
...
+    fn attribute() -> Attribute {
+        Attribute::WRITABLE | Attribute::NON_ENUMERABLE | Attribute::CONFIGURABLE
+    }
+
+    fn init(context: &mut Context) -> (&'static str, Value, Attribute) {
+        let _timer = BoaProfiler::global().start_event(Self::NAME, "init");
 
+        let error_prototype = context.standard_objects().error_object().prototype();
+        let attribute = Attribute::WRITABLE | Attribute::NON_ENUMERABLE | Attribute::CONFIGURABLE;
+        let range_error_object = ConstructorBuilder::with_standard_object(
```
Comment (RageKnify) [inline boa/src/builtins/error/type.rs:41]: `range_error_object` should be `type_error_object`, right?

File: boa/src/builtins/error/syntax.rs [hunk 6]
```diff
@@ -12,25 +12,51 @@
...
+    fn attribute() -> Attribute {
+        Attribute::WRITABLE | Attribute::NON_ENUMERABLE | Attribute::CONFIGURABLE
+    }
+
+    fn init(context: &mut Context) -> (&'static str, Value, Attribute) {
+        let _timer = BoaProfiler::global().start_event(Self::NAME, "init");
 
+        let error_prototype = context.standard_objects().error_object().prototype();
+        let attribute = Attribute::WRITABLE | Attribute::NON_ENUMERABLE | Attribute::CONFIGURABLE;
+        let range_error_object = ConstructorBuilder::with_standard_object(
```
Comment (RageKnify) [inline boa/src/builtins/error/syntax.rs:38]: `range_error_object` should be `syntax_error_object`, like in `type.rs`

File: boa/src/builtins/error/reference.rs [hunk 7]
```diff
@@ -10,24 +10,50 @@
...
+    fn attribute() -> Attribute {
+        Attribute::WRITABLE | Attribute::NON_ENUMERABLE | Attribute::CONFIGURABLE
+    }
+
+    fn init(context: &mut Context) -> (&'static str, Value, Attribute) {
+        let _timer = BoaProfiler::global().start_event(Self::NAME, "init");
 
+        let error_prototype = context.standard_objects().error_object().prototype();
+        let attribute = Attribute::WRITABLE | Attribute::NON_ENUMERABLE | Attribute::CONFIGURABLE;
+        let range_error_object = ConstructorBuilder::with_standard_object(
```
Comment (RageKnify) [inline boa/src/builtins/error/reference.rs:35]: `range_error_object` should be `reference_error_object`

**Review by RageKnify — CHANGES_REQUESTED** [review]
There are some typos and a few things I didn't fully understand.

File: boa/src/builtins/mod.rs [hunk 8]
```diff
@@ -27,61 +27,72 @@ pub(crate) use self::{
...
 
 /// Initializes builtin objects and functions
 #[inline]
-pub fn init(interpreter: &mut Context) {
-    let globals = [
-        // The `Function` global must be initialized before other types.
-        function::init,
-        Object::init,
+pub fn init(context: &mut Context) {
+    let globals2 = [
```
[the remark this answers is not in the document]
Comment (HalidOdat) [reply boa/src/builtins/mod.rs:60]: > Any reason to change the name from `globals` to `globals2`?

What was when I transitioning to the cached standard objects, I'll change it :)

File: boa/src/object/internal_methods.rs (hunk 1 above)
Comment (HalidOdat) [reply boa/src/object/internal_methods.rs:339]: > `Object::insert` inserts a `Property`, but `Object::insert_property`, inserts `V: Into<Value>`.
> Seems pretty confusing to me, should switch them up, no?

Its is kind of confuzing but `inset` does not insert a property it inserts a Property Descriptor (this is why `Property` should be called `PropertyDescriptor` which is the way object as stored as a `HashMap<PropertyKey, PropertyDescriptor>`), and `insert_property` inserts a property like `x: "foo"`

File: boa/src/context.rs (hunk 2 above)
Comment (HalidOdat) [reply boa/src/context.rs:153]: > *have to _**be**_ in the same thread.

typo :sweat_smile:

File: boa/src/class.rs (hunk 3 above)
Comment (HalidOdat) [reply boa/src/class.rs:135]: > Can you detail the `TODO` or was it from when you were implementing it?

It was something I wanted to implement, I'll do it now :)

File: boa/src/builtins/map/mod.rs (hunk 4 above)
Comment (HalidOdat) [reply boa/src/builtins/map/mod.rs:56]: > Should be `"this is map object"`, right?

It was there before i started changing things, I'll change it

File: boa/src/builtins/error/syntax.rs (hunk 6 above)
Comment (HalidOdat) [reply boa/src/builtins/error/syntax.rs:38]: same here

File: boa/src/builtins/error/reference.rs (hunk 7 above)
Comment (HalidOdat) [reply boa/src/builtins/error/reference.rs:35]: and here

File: boa/src/builtins/error/type.rs (hunk 5 above)
Comment (HalidOdat) [reply boa/src/builtins/error/type.rs:41]: Copy paste mistake

**Review by RageKnify — APPROVED** [review]

**Comment by JohnDoneth** [comment]
I like the switch to builders instead of calling `make_builtin_fn` and like functions a bunch. Code is clear and concise! 👍
