### PR TITLE
fix(engine): replace str::replace with cow_replace in module loader

### LINKED ISSUE #5140: Remaining `str::replace` usage flagged by clippy::disallowed_methods in module loader
While running `cargo make run-ci`, clippy reports a `disallowed_methods` warning for:

core/engine/src/module/loader/mod.rs:65

    let specifier = specifier.replace('/', "\\");

Since #4123 migrated similar cases to `cow_utils::CowUtils::cow_replace` to avoid unnecessary allocations, this looks like a remaining instance.

I’d like to send a small PR replacing this with `cow_replace`.

### PR DESCRIPTION
**Pull request by iammdzaidalam**
Closes #5140

Replaces `str::replace` with `cow_utils::CowUtils::cow_replace` in the module loader to satisfy `clippy::disallowed_methods` and avoid unnecessary allocation.

Follows the pattern introduced in #4123.

### CODE REVIEW

File: core/engine/src/module/loader/mod.rs [hunk 1]
```diff
@@ -62,7 +64,7 @@ pub fn resolve_module_specifier(
 
     // On Windows, also replace `/` with `\`. JavaScript imports use `/` as path separator.
     #[cfg(target_family = "windows")]
-    let specifier = specifier.replace('/', "\\");
+    let specifier = specifier.cow_replace('/', "\\").into_owned();
```
Comment (jedel1043) [inline core/engine/src/module/loader/mod.rs]: It would be better to use the trait directly instead of importing
```
cow_utils::CowUtils::cow_replace(specifier, '/', "\\")
```
Also, using `cow_replace` then `into_owned` immediately after is... an interesting decision, because it's basically nullifying the use of `cow_replace`.

**Review by jedel1043 — APPROVED** [review]
LGTM

File: core/engine/src/module/loader/mod.rs (hunk 1 above)
Comment (iammdzaidalam) [reply core/engine/src/module/loader/mod.rs]: Thanks, resolved 👍
