### PR TITLE
Make `Array.prototype.concat` spec compliant

### LINKED ISSUE #1306: Some Test262 tests run forever
**Describe the bug**
We are ignoring some Test262 tests because they run forever. Here you have the list of them:

 - [`test/built-ins/String/prototype/padStart/fill-string-empty.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/String/prototype/padStart/fill-string-empty.js)
 - [`test/built-ins/String/prototype/padEnd/fill-string-empty.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/String/prototype/padEnd/fill-string-empty.js)
 - [`test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-1.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-1.js)
 - [`test/built-ins/Array/prototype/unshift/throws-if-integer-limit-exceeded.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/unshift/throws-if-integer-limit-exceeded.js)
 - [`test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js)
 - [`test/built-ins/Array/prototype/includes/length-boundaries.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/includes/length-boundaries.js)

**To Reproduce**
You can reproduce any of them by running the following command after removing them from the `test_ignore.txt` file:
```bash
cargo run --release --bin boa_tester -- run -s {test_path}
```

**Expected behavior**
These tests should run reasonably fast (usually not more than a second), but they run forever. A fix should make this happen. Some of them might be easier to fix than others.

### PR DESCRIPTION
**Pull request by neeldug**
This Pull Request fixes/closes #1306.

It changes the following:

- adds limit checks to array concat
- still fails test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js due to Proxy not being implemented
- no longer runs forever

### CODE REVIEW

**Comment by neeldug** [comment]
Only thing would be I think the way I define spreadable isn’t super spec compliant, and perhaps we should create a utility function for isConcatSpreadable?

**Comment by Razican** [comment]
> Only thing would be I think the way I define spreadable isn’t super spec compliant, and perhaps we should create a utility function for isConcatSpreadable?

I think it makes sense, if it would make it more spec compliant.

**Comment by Razican** [comment]
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 26,941 | 26,941 | 0 |
  | Ignored | 15,628 | 15,626 | **-2** |
  | Failed | 36,328 | 36,330 | **+2** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 34.15% | 34.15% | 0.00% |
  
  <details><summary><b>Broken tests:</b></summary>
  
  ```
  test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js [strict mode] (previously Ignored)
  test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js (previously Ignored)
  ```
  </details>

**Review by Razican — APPROVED** [review]

**Comment by neeldug** [comment]
> I think it makes sense, if it would make it more spec compliant.

@Razican I've been working on creating the utility function is_concat_spreadable, but haven't quite worked out how to access the attribute [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/isConcatSpreadable) from `Value` using the `WellKnownSymbol`, would it be correct in matching over `match this.get_property(spreadable)`, where spreadable is the `WellKnownSymbol`

**Comment by neeldug** [comment]
@Razican this should be merged, it's waiting on #1300 for it to pass, but it no longer stalls, and in fact passes the first half.

**Comment by neeldug** [comment]
@Razican when you get the chance, could you check this PR, the test is failing due to proxies not being implemented, but the function is working as expected for the first part of the test-case, we could wait for #1300 to be resolved before merging, but as it's a test, I'm not sure if that's necessary.

**Review by Razican — APPROVED** [review]
Thanks! Let's merge it and wait for Buffer objects in order to fix the test.

File: boa/src/builtins/array/mod.rs [hunk 1]
```diff
@@ -276,6 +276,30 @@ impl Array {
         Ok(array_obj_ptr)
     }
 
+    /// Utility function for concatenating array objects.
+    ///
+    /// Returns a Boolean valued property that if `true` indicates that
+    /// an object should be flattened to its array elements
+    /// by `Array.prototype.concat`.
+
+    pub(crate) fn is_concat_spreadable(this: &Value, context: &mut Context) -> bool {
```
Comment (HalidOdat) [inline boa/src/builtins/array/mod.rs:285]: `is_concat_spreadable` should return `Result<bool>` since in the spec it says:
```text
Let spreadable be ? Get(O, @@isConcatSpreadable).
```

File: boa/src/builtins/array/mod.rs [hunk 2]
```diff
@@ -276,6 +276,30 @@ impl Array {
         Ok(array_obj_ptr)
     }
 
+    /// Utility function for concatenating array objects.
+    ///
+    /// Returns a Boolean valued property that if `true` indicates that
+    /// an object should be flattened to its array elements
+    /// by `Array.prototype.concat`.
+
```
Comment (HalidOdat) [inline boa/src/builtins/array/mod.rs:284]:
```suggestion
```

unnecessary empty line

File: boa/src/builtins/array/mod.rs [hunk 3]
```diff
@@ -276,6 +276,29 @@ impl Array {
...
+    /// Returns a Boolean valued property that if `true` indicates that
+    /// an object should be flattened to its array elements
+    /// by `Array.prototype.concat`.
+    pub(crate) fn is_concat_spreadable(this: &Value, context: &mut Context) -> Result<bool> {
+        if !this.is_object() {
+            return Ok(false);
+        }
+        let spreadable = this
+            .get_field(WellKnownSymbols::is_concat_spreadable(), context)
+            .unwrap_or_else(|_| Value::undefined());
```
Comment (HalidOdat) [inline boa/src/builtins/array/mod.rs:290]:
```suggestion
            .get_field(WellKnownSymbols::is_concat_spreadable(), context)?;
```
It should propagate the exception according to spec

File: boa/src/builtins/array/mod.rs [hunk 4]
```diff
@@ -276,6 +276,29 @@ impl Array {
         Ok(array_obj_ptr)
     }
 
+    /// Utility function for concatenating array objects.
+    ///
+    /// Returns a Boolean valued property that if `true` indicates that
+    /// an object should be flattened to its array elements
+    /// by `Array.prototype.concat`.
+    pub(crate) fn is_concat_spreadable(this: &Value, context: &mut Context) -> Result<bool> {
+        if !this.is_object() {
```
Comment (HalidOdat) [inline boa/src/builtins/array/mod.rs:285]:
```suggestion
		// 1. If Type(O) is not Object, return false.
        if !this.is_object() {
```
It would be nice to document according to spec.

**Comment by HalidOdat** [comment]
| Test result | master count | PR count | difference |
| :---------: | :----------: | :------: | :--------: |
| Total | 78,897 | 78,897 | 0 |
| Passed | 27,954 | 27,954 | 0 |
| Ignored | 15,616 | 15,614 | **-2** |
| Failed | 35,327 | 35,329 | **+2** |
| Panics | 0 | 0 | 0 |
| Conformance | 35.43% | 35.43% | 0.00% |

<details><summary><b>Broken tests:</b></summary>

```
test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js [strict mode] (previously Ignored)
test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js (previously Ignored)
```
</details>

**Review by HalidOdat — COMMENTED** [review]
I think it's best to make `Array.prototype.concat` spec compliant like some that were done in #1422, we have all the necessary spec function (like `length_of_array_like`) so we don't use functions like `.get_field`, which we should deprecate/remove in the near future #577 .

**Comment by neeldug** [comment]
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 28,432 | 28,474 | **+42** |
  | Ignored | 15,614 | 15,612 | **-2** |
  | Failed | 34,851 | 34,811 | **-40** |
  | Panics | 2 | 2 | 0 |
  | Conformance | 36.04% | 36.09% | **+0.05%** |
  
  <details><summary><b>Fixed tests:</b></summary>
  
  ```
  test/built-ins/Array/prototype/concat/create-species-non-ctor.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-non-ctor.js (previously Failed)
  test/built-ins/Array/prototype/concat/S15.4.4.4_A1_T3.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/S15.4.4.4_A1_T3.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-non-array.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-non-array.js (previously Failed)
  test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-getter-throws.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-getter-throws.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-with-non-configurable-property-spreadable.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-with-non-configurable-property-spreadable.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-with-non-configurable-property.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-with-non-configurable-property.js (previously Failed)
  test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like.js (previously Failed)
  test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T3.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T3.js (previously Failed)
  test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T1.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T1.js (previously Failed)
  test/built-ins/Array/prototype/concat/S15.4.4.4_A2_T2.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/S15.4.4.4_A2_T2.js (previously Failed)
  test/built-ins/Array/prototype/concat/is-concat-spreadable-get-err.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/is-concat-spreadable-get-err.js (previously Failed)
  test/built-ins/Array/prototype/concat/call-with-boolean.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/call-with-boolean.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-proto-from-ctor-realm-non-array.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-proto-from-ctor-realm-non-array.js (previously Failed)
  test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-reg-exp.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-reg-exp.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-ctor-non-object.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-ctor-non-object.js (previously Failed)
  test/built-ins/Array/prototype/concat/is-concat-spreadable-val-falsey.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/is-concat-spreadable-val-falsey.js (previously Failed)
  test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-function.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-function.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-poisoned.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-poisoned.js (previously Failed)
  test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T2.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T2.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-ctor-poisoned.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-ctor-poisoned.js (previously Failed)
  test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-string-length.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-string-length.js (previously Failed)
  test/built-ins/Array/prototype/concat/15.4.4.4-5-c-i-1.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/15.4.4.4-5-c-i-1.js (previously Failed)
  ```
  </details>
  
  <details><summary><b>Broken tests:</b></summary>
  
  ```
  test/built-ins/Array/prototype/concat/create-proto-from-ctor-realm-array.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/concat/create-proto-from-ctor-realm-array.js (previously Passed)
  test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js [strict mode] (previously Ignored)
  test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js (previously Ignored)
  ```
  </details>

File: boa/src/builtins/array/mod.rs [hunk 5]
```diff
@@ -461,30 +488,68 @@ impl Array {
...
+        let obj = this.to_object(context)?;
+        // 2. Let A be ? ArraySpeciesCreate(O, 0).
+        let arr = Self::array_species_create(&obj, 0, context)?;
+        // 3. Let n be 0.
+        let mut n = 0;
+        // 4. Prepend O to items.
+        let mut items = args
+            .iter()
+            .flat_map(|item_val| item_val.to_object(context))
+            .collect::<VecDeque<GcObject>>();
```
Comment (neeldug) [inline boa/src/builtins/array/mod.rs:501]: @Razican @HalidOdat Was hoping to get your input on whether I should use a VecDeque, ran a benchmark against both types with no consistent result proving better or worse.

File: boa/src/builtins/array/mod.rs [hunk 6]
```diff
@@ -461,30 +488,68 @@ impl Array {
...
+                for k in 0..len {
+                    // 1. Let P be ! ToString(𝔽(k)).
+                    // 2. Let exists be ? HasProperty(E, P).
+                    let exists = item.has_property(k, context)?;
+                    // 3. If exists is true, then
+                    if exists {
+                        // a. Let subElement be ? Get(E, P).
+                        let sub_element = item.get(k, context)?;
+                        // b. Perform ? CreateDataPropertyOrThrow(A, ! ToString(𝔽(n)), subElement).
+                        arr.create_data_property_or_throw(n, sub_element, context)?;
```
Comment (HalidOdat) [inline boa/src/builtins/array/mod.rs:528]: since we want an object, so we can call `.has_property()`, in `HasProperty` it says `1. Assert: Type(O) is Object.`, so we now at this point after `IsConcatSeparatable()` checks if it is an object we can call `.unwrap()`. since there is not chance that it can't be an object.

```suggestion
					// item is guaranteed to be an object since is_concat_separable checks it,
					// so we can call `.unwrap()`
					let item = item.as_object().unwrap();
                    // 1. Let P be ! ToString(𝔽(k)).
                    // 2. Let exists be ? HasProperty(E, P).
                    let exists = item.has_property(k, context)?;
                    // 3. If exists is true, then
                    if exists {
                        // a. Let subElement be ? Get(E, P).
                        let sub_element = item.get(k, context)?;
                        // b. Perform ? CreateDataPropertyOrThrow(A, ! ToString(𝔽(n)), subElement).
                        arr.create_data_property_or_throw(n, sub_element, context)?;
```

File: boa/src/builtins/array/mod.rs [hunk 7]
```diff
@@ -286,6 +287,32 @@ impl Array {
         Ok(array_obj_ptr)
     }
 
+    /// Utility function for concatenating array objects.
+    ///
+    /// Returns a Boolean valued property that if `true` indicates that
+    /// an object should be flattened to its array elements
+    /// by `Array.prototype.concat`.
+    fn is_concat_spreadable(this: &GcObject, context: &mut Context) -> Result<bool> {
+        // 1. If Type(O) is not Object, return false.
```
[the remark this answers is not in the document]
Comment (neeldug) [reply boa/src/builtins/array/mod.rs:296]: But it now needs to accept &GcObject for spec compliance right?

[the remark this answers is not in the document]
Comment (HalidOdat) [reply boa/src/builtins/array/mod.rs:296]: > But it now needs to accept &GcObject for spec compliance right?

In the spec it says:
```
1. If Type(O) is not Object, return false.
2. Let spreadable be ? Get(O, @@isConcatSpreadable).
3. If spreadable is not undefined, return ! ToBoolean(spreadable).
4. Return ? IsArray(O).
```

It does not say `1. Assert: Type(O) is Object.` which means it always is an object, rather it says `1. If Type(O) is not Object, return false` Which means it could a value which is not an object, in that case return false. So the previous implementation was more spec compliant.

[the remark this answers is not in the document]
Comment (neeldug) [reply boa/src/builtins/array/mod.rs]: Yep, that's my bad... Sorry about that!

File: boa/src/builtins/array/mod.rs [hunk 8]
```diff
@@ -292,25 +291,32 @@ impl Array {
...
 
     /// `LengthOfArrayLike ( obj )`
     ///
     /// The abstract operation LengthOfArrayLike takes argument obj.
     /// It returns the value of the "length" property of an array-like object (as a non-negative integer).
 
-    fn length_of_array_like(this: &GcObject, context: &mut Context) -> Result<usize> {
-        this.get("length", context)?.to_length(context)
+    fn length_of_array_like(this: &Value, context: &mut Context) -> Result<usize> {
+        this.get_field("length", context)?.to_length(context)
```
Comment (HalidOdat) [inline boa/src/builtins/array/mod.rs:319]: we already have an implementation of `length_of_array_like` in `GcObject` as a method.

File: boa/src/builtins/array/mod.rs [hunk 9]
```diff
@@ -495,11 +501,8 @@ impl Array {
...
         // 4. Prepend O to items.
-        let mut items = args
-            .iter()
-            .flat_map(|item_val| item_val.to_object(context))
-            .collect::<VecDeque<GcObject>>();
-        items.push_front(obj);
+        let mut items = vec![Value::from(this)];
+        items.extend_from_slice(args);
         // 5. For each element E of items, do
         for item in items {
```
Comment (HalidOdat) [inline boa/src/builtins/array/mod.rs]: Why do we add `this` to the items, the this value is separate from items argument, this is just `args: &[Value]`

Comment (neeldug) [reply boa/src/builtins/array/mod.rs]: It says to prepend this to items?

Comment (neeldug) [reply boa/src/builtins/array/mod.rs]: In step 4.

Comment (HalidOdat) [reply boa/src/builtins/array/mod.rs]: > It says to prepend this to items?
> `4. Prepend O to items.`, hence why I figured items must be an array of objects.

Ah, sorry missed that. But we should append `obj` not `this` since it is the result of `.to_object()`.

Also we should be able to do something like:
```rust
for item in [obj.into()].chain(args) {
```
so we do not allocate an vec.

Comment (neeldug) [reply boa/src/builtins/array/mod.rs]: @HalidOdat Unless I'm misunderstanding something, this is how we'd expect concat to work, where it would join the left and right?

Comment (HalidOdat) [reply boa/src/builtins/array/mod.rs]: > @HalidOdat Unless I'm misunderstanding something, this is how we'd expect concat to work, where it would join the left and right?

Could you explain what you mean? `[obj.into()].chain(args)` this just joins to rust iterators together.

Comment (neeldug) [reply boa/src/builtins/array/mod.rs]: > > It says to prepend this to items?
> > `4. Prepend O to items.`, hence why I figured items must be an array of objects.
> 
> Ah, sorry missed that. But we should append `obj` not `this` since it is the result of `.to_object()`.

But this seems kind of backwards, we initially convert this, from a Value to an Object, and then convert it back to a value for some reason? Instead of just using the Value from before?

Comment (HalidOdat) [reply boa/src/builtins/array/mod.rs]: > But this seems kind of backwards, we initially convert this, from a Value to an Object, and then convert it back to a value for some reason? Instead of just using the Value from before?

The `this` could be an object but it could also we a string for example depeands on how we call it (`Array.prototype.call("I am a string")`), but `obj` will always we a object since it is returned from `to_object()`

**Comment by HalidOdat** [comment]
| Test result | master count | PR count | difference |
| :---------: | :----------: | :------: | :--------: |
| Total | 78,897 | 78,897 | 0 |
| Passed | 28,432 | 28,484 | **+52** |
| Ignored | 15,614 | 15,612 | **-2** |
| Failed | 34,851 | 34,801 | **-50** |
| Panics | 2 | 2 | 0 |
| Conformance | 36.04% | 36.10% | **+0.07%** |

<details><summary><b>Fixed tests:</b></summary>

```
test/built-ins/Array/prototype/concat/S15.4.4.4_A1_T2.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A1_T2.js (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-number-wrapper.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-number-wrapper.js (previously Failed)
test/built-ins/Array/prototype/concat/create-species-with-non-writable-property.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/create-species-with-non-writable-property.js (previously Failed)
test/built-ins/Array/prototype/concat/create-species-non-ctor.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/create-species-non-ctor.js (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A1_T3.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A1_T3.js (previously Failed)
test/built-ins/Array/prototype/concat/create-non-array.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/create-non-array.js (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-getter-throws.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-getter-throws.js (previously Failed)
test/built-ins/Array/prototype/concat/create-species-with-non-configurable-property-spreadable.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/create-species-with-non-configurable-property-spreadable.js (previously Failed)
test/built-ins/Array/prototype/concat/create-species-with-non-configurable-property.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/create-species-with-non-configurable-property.js (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like.js (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T3.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T3.js (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T1.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T1.js (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A2_T2.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A2_T2.js (previously Failed)
test/built-ins/Array/prototype/concat/is-concat-spreadable-get-err.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/is-concat-spreadable-get-err.js (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-boolean-wrapper.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-boolean-wrapper.js (previously Failed)
test/built-ins/Array/prototype/concat/call-with-boolean.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/call-with-boolean.js (previously Failed)
test/built-ins/Array/prototype/concat/create-proto-from-ctor-realm-non-array.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/create-proto-from-ctor-realm-non-array.js (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A2_T1.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A2_T1.js (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-reg-exp.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-reg-exp.js (previously Failed)
test/built-ins/Array/prototype/concat/create-ctor-non-object.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/create-ctor-non-object.js (previously Failed)
test/built-ins/Array/prototype/concat/is-concat-spreadable-val-falsey.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/is-concat-spreadable-val-falsey.js (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-function.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-function.js (previously Failed)
test/built-ins/Array/prototype/concat/create-species-poisoned.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/create-species-poisoned.js (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T2.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T2.js (previously Failed)
test/built-ins/Array/prototype/concat/create-ctor-poisoned.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/create-ctor-poisoned.js (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-string-length.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-string-length.js (previously Failed)
test/built-ins/Array/prototype/concat/15.4.4.4-5-c-i-1.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/15.4.4.4-5-c-i-1.js (previously Failed)
```
</details>

<details><summary><b>Broken tests:</b></summary>

```
test/built-ins/Array/prototype/concat/create-proto-from-ctor-realm-array.js [strict mode] (previously Passed)
test/built-ins/Array/prototype/concat/create-proto-from-ctor-realm-array.js (previously Passed)
test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js [strict mode] (previously Ignored)
test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js (previously Ignored)
```
</details>

**Review by HalidOdat — COMMENTED** [review]
I think we should remove the array_cancat benchmarks since, we already have benchmarks about array access.

Besides that it looks good to me :)

**Review by HalidOdat — APPROVED** [review]
