### PR TITLE
Fix `Number.toExponential` and `Number.toFixed`

### LINKED ISSUE #1602: Fix `Number.toExponential` and `Number.toFixed`
The functions `toExponential` and `toFixed` of the `Number` prototype are currently not implemented spec compliant. All of the tests for those two functions should pass if they do not rely on other features that are not implemented.

To see the exact failed tests, take a look at the current results at https://boa-dev.github.io/boa/test262/

Spec references:
- https://tc39.es/ecma262/#sec-number.prototype.toexponential
- https://tc39.es/ecma262/#sec-number.prototype.tofixed

### PR DESCRIPTION
**Pull request by nrabulinski**
This Pull Request closes #1602.

It makes `toExponential` and `toFixed` methods on `Number` compliant with the specification.

One of the tests in `toExponential` currently fails. This is something that's blocked by https://github.com/rust-lang/rust/issues/89493, unless we were to implement the exponential string algorithm ourselves.

### CODE REVIEW

**Comment by raskad** [comment]
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 80,930 | 80,930 | 0 |
  | Passed | 33,364 | 33,388 | **+24** |
  | Ignored | 15,898 | 15,898 | 0 |
  | Failed | 31,668 | 31,644 | **-24** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 41.23% | 41.26% | **+0.03%** |
  
  <details><summary><b>Fixed tests (24):</b></summary>
  
  ```
  test/built-ins/Number/prototype/toFixed/S15.7.4.5_A1.4_T01.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toFixed/S15.7.4.5_A1.4_T01.js (previously Failed)
  test/built-ins/Number/prototype/toFixed/range.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toFixed/range.js (previously Failed)
  test/built-ins/Number/prototype/toFixed/S15.7.4.5_A1.3_T01.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toFixed/S15.7.4.5_A1.3_T01.js (previously Failed)
  test/built-ins/Number/prototype/toFixed/S15.7.4.5_A1.3_T02.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toFixed/S15.7.4.5_A1.3_T02.js (previously Failed)
  test/built-ins/Number/prototype/toExponential/return-abrupt-tointeger-fractiondigits-symbol.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toExponential/return-abrupt-tointeger-fractiondigits-symbol.js (previously Failed)
  test/built-ins/Number/prototype/toExponential/this-is-0-fractiondigits-is-0.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toExponential/this-is-0-fractiondigits-is-0.js (previously Failed)
  test/built-ins/Number/prototype/toExponential/range.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toExponential/range.js (previously Failed)
  test/built-ins/Number/prototype/toExponential/this-is-0-fractiondigits-is-not-0.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toExponential/this-is-0-fractiondigits-is-not-0.js (previously Failed)
  test/built-ins/Number/prototype/toExponential/return-abrupt-tointeger-fractiondigits.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toExponential/return-abrupt-tointeger-fractiondigits.js (previously Failed)
  test/built-ins/Number/prototype/toExponential/infinity.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toExponential/infinity.js (previously Failed)
  test/built-ins/Number/prototype/toExponential/undefined-fractiondigits.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toExponential/undefined-fractiondigits.js (previously Failed)
  test/built-ins/Number/prototype/toExponential/tointeger-fractiondigits.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toExponential/tointeger-fractiondigits.js (previously Failed)
  ```
  </details>

File: boa/src/builtins/number/mod.rs [hunk 1]
```diff
@@ -254,13 +287,23 @@ impl Number {
...
+                    return Err(context.construct_range_error(
+                        "toFixed() digits argument must be between 0 and 100",
+                    ))
+                }
             },
             None => 0,
         };
-        let this_fixed_num = format!("{:.*}", precision, this_num);
-        Ok(JsValue::new(this_fixed_num))
+        // Get rid of the '-' sign for -0.0
```
Comment (raskad) [inline boa/src/builtins/number/mod.rs:299]: Step 6 from the spec seems to be missing here: `If x is not finite, return ! Number::toString(x).`
If you run `Infinity.toFixed()` the return is `"inf"` while it should be `"Infinity"`. I think there should be a 262 test for that, maybe we can get one added.

I would also suggest to add the spec as comments like in `parse_int`. That makes it very easy to read code and spec at the same time and see where and how they differ.

**Review by raskad — CHANGES_REQUESTED** [review]

**Comment by raskad** [comment]
Regarding the one failing test; I think we should merge this without that one.

But we may have an easier solution that to fix the issues in `std`. We already use [`ryu-js`](https://crates.io/crates/ryu-js) crate that converts numbers to strings. Conveniently the repository for the crate is in the boa-dev org: https://github.com/boa-dev/ryu-js ;)

Without looking further into it, my idea would be to implement the functionality of `num_to_exponential` and `num_to_exponential_with_precision` there. @HalidOdat I think you probably know the most about this, do you think we should try to do that, or is `ryu-js` not the right place?

File: boa/src/builtins/number/mod.rs [hunk 2]
```diff
@@ -214,6 +214,21 @@ impl Number {
...
 
+    /// Helper function that formats a float as a ES6-style exponential number string with a given precision.
+    // We can't use the same approach as in `num_to_exponential`
+    // because in cases like (0.999).toExponential(0) the result will be 1e0.
+    // Instead we get the index of 'e', and if the next character is not '-' we insert the plus sign
+    fn num_to_exponential_with_precision(n: f64, prec: usize) -> String {
+        let mut res = format!("{:.*e}", prec, n);
+        let idx = res
+            .find('e')
+            .unwrap_or_else(|| unreachable!("'e' not found in exponential string"));
```
[the remark this answers is not in the document]
Comment (nrabulinski) [reply boa/src/builtins/number/mod.rs:225]: My motivation for doing that was to eventually change it to `std::hint::unreachable_unchecked` as the resulting string **has** to contain "e" which is at most second to last, same with switching `res.as_bytes()[idx + 1]` to a `get_unchecked`. I understand and respect if that's not the direction you want to take though.

File: boa/src/builtins/number/mod.rs (hunk 1 above)
Comment (nrabulinski) [reply boa/src/builtins/number/mod.rs:299]: Ah, you're right, I actually planned on implementing that since there is a test for it in `toExponential` implementation and I saw it in the spec. I must've forgotten, I'm sorry.

File: boa/src/builtins/number/mod.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (raskad) [reply boa/src/builtins/number/mod.rs:225]: I see what you mean. I don't think we should use any non-required unsafe right now, but when our focus moves from spec compliance to performance that pattern for sure seems to be nice.

**Review by raskad — APPROVED** [review]
Looks good to me!

File: boa/src/builtins/number/mod.rs [hunk 3]
```diff
@@ -214,6 +214,19 @@ impl Number {
         }
     }
 
+    /// Helper function that formats a float as a ES6-style exponential number string with a given precision.
+    // We can't use the same approach as in `num_to_exponential`
+    // because in cases like (0.999).toExponential(0) the result will be 1e0.
+    // Instead we get the index of 'e', and if the next character is not '-' we insert the plus sign
+    fn num_to_exponential_with_precision(n: f64, prec: usize) -> String {
```
Comment (jedel1043) [inline boa/src/builtins/number/mod.rs:221]:
```suggestion
    fn to_exponential_with_precision(n: f64, prec: usize) -> String {
```

I'd rename `num_to_exponential` to `f64_to_exponential` and `num_to_exponential_with_precision` to `f64_to_exponential_with_precision`, and extract them as standalone functions. They don't need to be associated functions if they're just used within this module and don't receive a `&self`.

**Review by jedel1043 — CHANGES_REQUESTED** [review]
Just a small nitpick I have about the utility functions

File: boa/src/builtins/number/mod.rs (hunk 3 above)
Comment (nrabulinski) [reply boa/src/builtins/number/mod.rs:221]: Sure, I agree, I just followed what was already in the codebase 😅

Comment (nrabulinski) [reply boa/src/builtins/number/mod.rs:221]: Actually, what about other helper functions that are in the `impl Number` block? Is there a threshold when a function should be extracted and when it should stay? And would you recommend extracting it out in the same file?

Comment (jedel1043) [reply boa/src/builtins/number/mod.rs:221]: If the function is only used internally and it doesn't need a `self` parameter, just put it as a standalone function; you can follow that rule.

We're still cleaning up some parts of the codebase, that's why there's not too much consistency about this 😅

Comment (jedel1043) [reply boa/src/builtins/number/mod.rs:221]: Yeah, helper functions can be on the same file

**Comment by nrabulinski** [comment]
Actually I just realized that there's another case which isn't covered by any 262 test and that's `(1.0).toExponential()`, which should return `1e+0` but returned `1e0` for us :smile:

**Review by jedel1043 — APPROVED** [review]
Great work!

**Comment by jedel1043** [comment]
> Actually I just realized that there's another case which isn't covered by any 262 test and that's `(1.0).toExponential()`, which should return `1e+0` but returned `1e0` for us 😄

Oh, that can be filed on the [test262 repo](https://github.com/tc39/test262)
