### PR TITLE
fix(boa): fix stringpad abstract operation

### LINKED ISSUE #1306: Some Test262 tests run forever
**Describe the bug**
We are ignoring some Test262 tests because they run forever. Here you have the list of them:

 - [`test/built-ins/String/prototype/padStart/fill-string-empty.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/String/prototype/padStart/fill-string-empty.js)
 - [`test/built-ins/String/prototype/padEnd/fill-string-empty.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/String/prototype/padEnd/fill-string-empty.js)
 - [`test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-1.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-1.js)
 - [`test/built-ins/Array/prototype/unshift/throws-if-integer-limit-exceeded.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/unshift/throws-if-integer-limit-exceeded.js)
 - [`test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js)
 - [`test/built-ins/Array/prototype/includes/length-boundaries.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/includes/length-boundaries.js)

**To Reproduce**
You can reproduce any of them by running the following command after removing them from the `test_ignore.txt` file:
```bash
cargo run --release --bin boa_tester -- run -s {test_path}
```

**Expected behavior**
These tests should run reasonably fast (usually not more than a second), but they run forever. A fix should make this happen. Some of them might be easier to fix than others.

### PR DESCRIPTION
**Pull request by neeldug**
This Pull Request fixes/closes #1306.

It changes the following:

- renames filter to filler in accordance with spec
- adds empty string check to StringPad function

### CODE REVIEW

**Comment by Razican** [comment]
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 26,940 | 26,945 | **+5** |
  | Ignored | 15,628 | 15,624 | **-4** |
  | Failed | 36,329 | 36,328 | **-1** |
  | Panics | 1 | 0 | **-1** |
  | Conformance | 34.15% | 34.15% | **+0.01%** |
  
  <details><summary><b>Fixed tests:</b></summary>
  
  ```
  test/built-ins/Map/prototype/keys/returns-iterator.js (previously Panic)
  test/built-ins/String/prototype/padStart/fill-string-empty.js [strict mode] (previously Ignored)
  test/built-ins/String/prototype/padStart/fill-string-empty.js (previously Ignored)
  test/built-ins/String/prototype/padEnd/fill-string-empty.js [strict mode] (previously Ignored)
  test/built-ins/String/prototype/padEnd/fill-string-empty.js (previously Ignored)
  ```
  </details>

File: boa/src/builtins/string/mod.rs [hunk 1]
```diff
@@ -918,13 +918,17 @@ impl String {
             return Value::from(primitive);
         }
 
-        let filter = fill_string.as_deref().unwrap_or(" ");
+        let filler = fill_string.as_deref().unwrap_or(" ");
+
+        if filler == "" {
```
Comment (Razican) [inline boa/src/builtins/string/mod.rs:923]: I would write `filler.is_empty()`, it will be a bit more performant, and I think it's more clear when reading through the code.

**Review by Razican — APPROVED** [review]
Looks good to me. But note that it only fixes two of the bugs mentioned in the issue. We still have some more to fix, so this won't close the issue.

Edit: nevermind, I just saw the rest of the fixes. If all of them are fixed, we can close the issue :) we just need to take care when merging, and make sure that all have been fixed.

**Review by RageKnify — APPROVED** [review]
