### PR TITLE
fix: Make StdClock monotonic using std::time::Instant

### LINKED ISSUE #4330: Implementation of `StdClock` is not monotonic.
According to [`JsInstant`'s documentation](https://github.com/boa-dev/boa/blob/e51fcd7f9637788c5e9e16f1e667f1fdfebef306/core/engine/src/context/time.rs#L1-L16):

> This type is guaranteed to be monotonic, i.e. if two instants are compared, the later one will always be greater than the earlier one. It is also always guaranteed to be greater than
or equal to the Unix epoch.

However, [`StdClock`'s implementation](https://github.com/boa-dev/boa/blob/e51fcd7f9637788c5e9e16f1e667f1fdfebef306/core/engine/src/context/time.rs#L141-L150) uses `SystemTime`, which on its [documentation](https://doc.rust-lang.org/stable/std/time/struct.SystemTime.html) specifies:

> Distinct from the [Instant](https://doc.rust-lang.org/stable/std/time/struct.Instant.html) type, this time measurement is not monotonic. This means that you can save a file to the file system, then save another file to the file system, and the second file has a SystemTime measurement earlier than the first. In other words, an operation that happens after another operation in real time may have an earlier SystemTime!

This makes it possible to break the invariants of `JsInstant`.

### PR DESCRIPTION
**Pull request by abhinavs1920**
This Pull Request fixes/closes #4330 .

Previously, `StdClock` used `SystemTime` which isn't monotonic—it can jump backward when the system clock adjusts. This broke the guarantees that `JsInstant` is supposed to provide for engine timing.

Now `StdClock` uses `std::time::Instant` with a base instant, measuring elapsed time from that point. This makes `JsInstant` truly monotonic like `std::time::Instant`, so time never goes backward for `setTimeout`, `setInterval`, and job scheduling.

For `Date` objects that need actual wall-clock time, I added a separate `system_time_millis()` method to the `Clock` trait. Clean separation of concerns.

Added tests to verify the monotonic behavior works as expected.

### CODE REVIEW

**Comment by abhinavs1920** [comment]
Heyy @jedel1043 , I have refactored the API design as we discussed. Please take a look when ever you are available :)

**Comment by abhinavs1920** [comment]
Heyy I have put pushed my latest commit, but it doesn't seem to be pushed here due to some github issue. 🥲

File: core/engine/src/context/time.rs [hunk 1]
```diff
@@ -1,5 +1,7 @@
 //! Clock related types and functions.
 
+use instant::Instant;
```
Comment (jedel1043) [inline core/engine/src/context/time.rs]: We already depend on `web-time`, and we have all the bindings on `crate::sys::time`, so you should be able to import `crate::sys::time::Instant`

File: core/engine/Cargo.toml [hunk 2]
```diff
@@ -139,6 +139,7 @@ either = { workspace = true, optional = true }
 static_assertions.workspace = true
 futures-channel.workspace = true
 aligned-vec.workspace = true
+instant.workspace = true
```
Comment (jedel1043) [inline core/engine/Cargo.toml]: Need to remove this dependency

File: Cargo.toml [hunk 3]
```diff
@@ -99,6 +99,7 @@ bus = "2.4.1"
 wasm-bindgen = { version = "0.2.97", default-features = false }
 getrandom = { version = "0.4.1", default-features = false }
 console_error_panic_hook = "0.1.7"
+instant = { version = "0.1", features = ["wasm-bindgen"] }
```
Comment (jedel1043) [inline Cargo.toml]: Also here, needs to be removed

**Review by jedel1043 — CHANGES_REQUESTED** [review]

File: Cargo.lock
Comment (jedel1043) [inline Cargo.lock:1]: please update the lock file

Comment (abhinavs1920) [reply Cargo.lock:1]: Updated Cargo.lock using cargo update. Does this look right?

File: core/engine/src/context/time.rs [hunk 4]
```diff
@@ -131,22 +145,62 @@ impl std::ops::Sub for JsInstant {
...
+    /// Returns the current wall-clock time in milliseconds since the Unix epoch.
+    ///
+    /// This is NOT monotonic and can go backward if the system clock is adjusted.
+    /// It should only be used for `Date` objects and other wall-clock time needs.
+    fn system_time_millis(&self) -> i64;
+}
+
+/// A clock that uses the standard monotonic clock.
+///
+/// This clock is based on [`instant::Instant`] which provides cross-platform
```
Comment (jedel1043) [inline core/engine/src/context/time.rs]: You should fix the documentation to reflect that we're using `web-time`.

File: core/engine/src/context/time.rs [hunk 5]
```diff
@@ -131,22 +145,62 @@ impl std::ops::Sub for JsInstant {
 
 /// Implement a clock that can be used to measure time.
 pub trait Clock {
-    /// Returns the current time.
+    /// Returns the current monotonic time.
+    ///
+    /// This is guaranteed to be monotonic and should be used for measuring
+    /// durations and scheduling timeouts.
```
Comment (jedel1043) [inline core/engine/src/context/time.rs]: Slight adjustment here. This is not guaranteed to be monotonic, the engine assumes it is monotonic, so the implementers of the trait are the ones that need to ensure the monotonicity of the returned `JsInstant`.

Comment (abhinavs1920) [reply core/engine/src/context/time.rs]: Thanks for the missed detail.. :)
