### PR TITLE
Fix tokenizing Unicode escape sequence in string literal

### LINKED ISSUE #808: A string containing only a Unicode escape sequence causes an error
**Describe the bug**
If a string is composed only of a Unicode escape sequence (e.g. `"\uABCD"`), then an error occurs instead of producing a string.

**To Reproduce**
```js
"\u00A7"
```
(that's the code for the section sign. It's not important, as the bug applies to any escape sequence)

**Expected behavior**
The string is valid, and is not supposed to throw an error. The syntax for string literals can be found [here](https://tc39.es/ecma262/#sec-literals-string-literals).

**Build environment (please complete the following information):**

- OS: `Windows 10`
- Version: `Version 1909 (OS Build 18363.1082)`
- Target triple: `x86_64-pc-windows-msvc`
- Rustc version: `rustc 1.46.0 (04488afe3 2020-08-24)`

**Additional context**
Spec: [https://tc39.es/ecma262/#sec-literals-string-literals](https://tc39.es/ecma262/#sec-literals-string-literals)
MDN: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar)

As far as I can tell, the bug is caused by an issue in [syntax/lexer/string.rs](https://github.com/boa-dev/boa/blob/master/boa/src/syntax/lexer/string.rs) where once a Unicode escape sequence is detected, it skips checking for `"` and believes the string has finished without a `"`.

### PR DESCRIPTION
**Pull request by jevancc**
This Pull Request fixes/closes #808 .

It changes the following:

- Add `InnerIter::peek_iter()` and store the peeked char in `InnerIter` instance instead of `Cursor`
- Fix invalid Unicode code point in lexer test

The issue is caused by a bug in `Cursor::fill_bytes`. When `Cursor::fill_bytes` was called after `Cursor::peek`, the iter would be incremented to peek the next char but the peeked char would not be filled to the buffer. This PR introduces a new method `InnerIter::peek_char` and stores the peeked char in `InnerIter` so that it can fill the peeked char to input buffer when invoking `InnerIter::fill_bytes` correctly.

The test `syntax::lexer::tests::codepoint_with_no_braces` is updated in this PR. Since `\uD83D` is a surrogate code point, the test will panic when calling `decode_utf16` and trying to decode it. This bug should be fixed in another issue/PR to handle the invalid code point.

### CODE REVIEW

File: boa/src/syntax/lexer/cursor.rs [hunk 1]
```diff
@@ -283,11 +292,13 @@ where
...
-        let next_byte = self.iter.next().transpose()?;
-
-        match next_byte {
-            Some(next) if next <= 0x7F => Ok(Some(next)),
-            None => Ok(None),
+        match self.next_char() {
+            Ok(Some(chr)) if chr.is_ascii() => {
+                let mut buf = [0u8; 4];
+                chr.encode_utf8(&mut buf);
+                Ok(Some(buf[0]))
```
Comment (HalidOdat) [inline boa/src/syntax/lexer/cursor.rs:299]:
```suggestion
                Ok(Some(chr as u8))
```
Couldn't we just cast to u8 since we check if its ascii, this should be faster than calling `encode_utf8`

**Review by HalidOdat — COMMENTED** [review]
Looks good to me!

File: boa/src/syntax/lexer/cursor.rs (hunk 1 above)
Comment (jevancc) [reply boa/src/syntax/lexer/cursor.rs]: Sounds great! I've made this change.

Comment (jevancc) [reply boa/src/syntax/lexer/cursor.rs]: Besides, I can look into the invalid code point issue. Is there already an issue/PR for it?

**Review by HalidOdat — APPROVED** [review]
Looks good to me! :)

File: boa/src/syntax/lexer/cursor.rs (hunk 1 above)
Comment (HalidOdat) [reply boa/src/syntax/lexer/cursor.rs]: > Besides, I can look into the invalid code point issue. Is there already an issue/PR for it?

There is an issue https://github.com/boa-dev/boa/issues/778, but not a PR to fix

**Review by Razican — APPROVED** [review]
It seems there are no regressions in the benchmarks, so this looks pretty good! Thanks!
